# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\01-NAD\Session-06\_pipeline\_utilities\_asset_manager\media\main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1063, 879)
        Form.setMinimumSize(QtCore.QSize(1050, 600))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Form.setMouseTracking(False)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet(_fromUtf8(""))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.assetManagerFrame = QtGui.QFrame(Form)
        self.assetManagerFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.assetManagerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.assetManagerFrame.setObjectName(_fromUtf8("assetManagerFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.assetManagerFrame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Tabs = QtGui.QTabWidget(self.assetManagerFrame)
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.assetLoaderTab = QtGui.QWidget()
        self.assetLoaderTab.setObjectName(_fromUtf8("assetLoaderTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.assetLoaderTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listFrame = QtGui.QFrame(self.assetLoaderTab)
        self.listFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.listFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.listFrame.setObjectName(_fromUtf8("listFrame"))
        self.gridLayout = QtGui.QGridLayout(self.listFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.departmentList = QtGui.QListWidget(self.listFrame)
        self.departmentList.setObjectName(_fromUtf8("departmentList"))
        self.gridLayout.addWidget(self.departmentList, 3, 1, 1, 1)
        self.filterLbl_3 = QtGui.QLabel(self.listFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filterLbl_3.setFont(font)
        self.filterLbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.filterLbl_3.setObjectName(_fromUtf8("filterLbl_3"))
        self.gridLayout.addWidget(self.filterLbl_3, 0, 2, 1, 1)
        self.projectList = QtGui.QListWidget(self.listFrame)
        self.projectList.setObjectName(_fromUtf8("projectList"))
        self.gridLayout.addWidget(self.projectList, 3, 0, 1, 1)
        self.filterLbl_4 = QtGui.QLabel(self.listFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filterLbl_4.setFont(font)
        self.filterLbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.filterLbl_4.setObjectName(_fromUtf8("filterLbl_4"))
        self.gridLayout.addWidget(self.filterLbl_4, 0, 4, 1, 1)
        self.assetList = QtGui.QListWidget(self.listFrame)
        self.assetList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assetList.setObjectName(_fromUtf8("assetList"))
        self.gridLayout.addWidget(self.assetList, 3, 4, 1, 1)
        self.seqList = QtGui.QListWidget(self.listFrame)
        self.seqList.setObjectName(_fromUtf8("seqList"))
        self.gridLayout.addWidget(self.seqList, 3, 2, 1, 1)
        self.filterLbl_2 = QtGui.QLabel(self.listFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filterLbl_2.setFont(font)
        self.filterLbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.filterLbl_2.setObjectName(_fromUtf8("filterLbl_2"))
        self.gridLayout.addWidget(self.filterLbl_2, 0, 1, 1, 1)
        self.filterLbl = QtGui.QLabel(self.listFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filterLbl.setFont(font)
        self.filterLbl.setTextFormat(QtCore.Qt.AutoText)
        self.filterLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.filterLbl.setObjectName(_fromUtf8("filterLbl"))
        self.gridLayout.addWidget(self.filterLbl, 0, 0, 1, 1)
        self.assetFilterFrame = QtGui.QFrame(self.listFrame)
        self.assetFilterFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.assetFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.assetFilterFrame.setLineWidth(1)
        self.assetFilterFrame.setObjectName(_fromUtf8("assetFilterFrame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.assetFilterFrame)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.assetFilterClearBtn = QtGui.QPushButton(self.assetFilterFrame)
        self.assetFilterClearBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.assetFilterClearBtn.setObjectName(_fromUtf8("assetFilterClearBtn"))
        self.horizontalLayout_5.addWidget(self.assetFilterClearBtn)
        self.assetFilter = QtGui.QLineEdit(self.assetFilterFrame)
        self.assetFilter.setObjectName(_fromUtf8("assetFilter"))
        self.horizontalLayout_5.addWidget(self.assetFilter)
        self.gridLayout.addWidget(self.assetFilterFrame, 2, 4, 1, 1)
        self.seqFilterFrame = QtGui.QFrame(self.listFrame)
        self.seqFilterFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.seqFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.seqFilterFrame.setObjectName(_fromUtf8("seqFilterFrame"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.seqFilterFrame)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.seqFilterClearBtn = QtGui.QPushButton(self.seqFilterFrame)
        self.seqFilterClearBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.seqFilterClearBtn.setIconSize(QtCore.QSize(16, 16))
        self.seqFilterClearBtn.setCheckable(False)
        self.seqFilterClearBtn.setDefault(False)
        self.seqFilterClearBtn.setFlat(False)
        self.seqFilterClearBtn.setObjectName(_fromUtf8("seqFilterClearBtn"))
        self.horizontalLayout_6.addWidget(self.seqFilterClearBtn)
        self.seqFilter = QtGui.QLineEdit(self.seqFilterFrame)
        self.seqFilter.setObjectName(_fromUtf8("seqFilter"))
        self.horizontalLayout_6.addWidget(self.seqFilter)
        self.gridLayout.addWidget(self.seqFilterFrame, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.listFrame)
        self.infoFrame = QtGui.QFrame(self.assetLoaderTab)
        self.infoFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.infoFrame.setObjectName(_fromUtf8("infoFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.infoFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.assetInfoGrp = QtGui.QGroupBox(self.infoFrame)
        self.assetInfoGrp.setObjectName(_fromUtf8("assetInfoGrp"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.assetInfoGrp)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.thumbnailFrame = QtGui.QFrame(self.assetInfoGrp)
        self.thumbnailFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.thumbnailFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.thumbnailFrame.setObjectName(_fromUtf8("thumbnailFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.thumbnailFrame)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.thumbnailFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.assetImg = QtGui.QLabel(self.thumbnailFrame)
        self.assetImg.setMinimumSize(QtCore.QSize(400, 200))
        self.assetImg.setMaximumSize(QtCore.QSize(1000, 200))
        self.assetImg.setAutoFillBackground(False)
        self.assetImg.setFrameShape(QtGui.QFrame.Box)
        self.assetImg.setFrameShadow(QtGui.QFrame.Raised)
        self.assetImg.setLineWidth(1)
        self.assetImg.setText(_fromUtf8(""))
        self.assetImg.setTextFormat(QtCore.Qt.AutoText)
        self.assetImg.setScaledContents(False)
        self.assetImg.setAlignment(QtCore.Qt.AlignCenter)
        self.assetImg.setWordWrap(False)
        self.assetImg.setObjectName(_fromUtf8("assetImg"))
        self.verticalLayout_4.addWidget(self.assetImg)
        self.updateThumbBtn = QtGui.QPushButton(self.thumbnailFrame)
        self.updateThumbBtn.setObjectName(_fromUtf8("updateThumbBtn"))
        self.verticalLayout_4.addWidget(self.updateThumbBtn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.thumbnailFrame)
        self.assetInfoFrame = QtGui.QFrame(self.assetInfoGrp)
        self.assetInfoFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.assetInfoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.assetInfoFrame.setObjectName(_fromUtf8("assetInfoFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.assetInfoFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_3 = QtGui.QFrame(self.assetInfoFrame)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.assetPathLbl = QtGui.QLabel(self.frame_3)
        self.assetPathLbl.setWordWrap(False)
        self.assetPathLbl.setObjectName(_fromUtf8("assetPathLbl"))
        self.horizontalLayout_2.addWidget(self.assetPathLbl)
        self.openInExplorerBtn = QtGui.QPushButton(self.frame_3)
        self.openInExplorerBtn.setObjectName(_fromUtf8("openInExplorerBtn"))
        self.horizontalLayout_2.addWidget(self.openInExplorerBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_8 = QtGui.QFrame(self.assetInfoFrame)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.fileTypeLbl = QtGui.QLabel(self.frame_8)
        self.fileTypeLbl.setObjectName(_fromUtf8("fileTypeLbl"))
        self.horizontalLayout_4.addWidget(self.fileTypeLbl)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_8)
        self.label = QtGui.QLabel(self.assetInfoFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.commentTxt = QtGui.QTextEdit(self.assetInfoFrame)
        self.commentTxt.setReadOnly(True)
        self.commentTxt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.commentTxt.setObjectName(_fromUtf8("commentTxt"))
        self.verticalLayout.addWidget(self.commentTxt)
        self.commentTxtLine = QtGui.QLineEdit(self.assetInfoFrame)
        self.commentTxtLine.setObjectName(_fromUtf8("commentTxtLine"))
        self.verticalLayout.addWidget(self.commentTxtLine)
        self.addCommentBtn = QtGui.QPushButton(self.assetInfoFrame)
        self.addCommentBtn.setObjectName(_fromUtf8("addCommentBtn"))
        self.verticalLayout.addWidget(self.addCommentBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.frame_3.raise_()
        self.label.raise_()
        self.addCommentBtn.raise_()
        self.commentTxtLine.raise_()
        self.commentTxt.raise_()
        self.frame_8.raise_()
        self.horizontalLayout.addWidget(self.assetInfoFrame)
        self.verticalLayout_3.addWidget(self.assetInfoGrp)
        self.actionGrpBox = QtGui.QGroupBox(self.infoFrame)
        self.actionGrpBox.setObjectName(_fromUtf8("actionGrpBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.actionGrpBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.actionFrame = QtGui.QFrame(self.actionGrpBox)
        self.actionFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.actionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.actionFrame.setObjectName(_fromUtf8("actionFrame"))
        self.actionFrameLayout = QtGui.QVBoxLayout(self.actionFrame)
        self.actionFrameLayout.setObjectName(_fromUtf8("actionFrameLayout"))
        self.verticalLayout_8.addWidget(self.actionFrame)
        self.verticalLayout_3.addWidget(self.actionGrpBox)
        self.verticalLayout_2.addWidget(self.infoFrame)
        self.createVersionBtn = QtGui.QPushButton(self.assetLoaderTab)
        self.createVersionBtn.setObjectName(_fromUtf8("createVersionBtn"))
        self.verticalLayout_2.addWidget(self.createVersionBtn)
        self.publishBtn = QtGui.QPushButton(self.assetLoaderTab)
        self.publishBtn.setObjectName(_fromUtf8("publishBtn"))
        self.verticalLayout_2.addWidget(self.publishBtn)
        self.loadBtn = QtGui.QPushButton(self.assetLoaderTab)
        self.loadBtn.setObjectName(_fromUtf8("loadBtn"))
        self.verticalLayout_2.addWidget(self.loadBtn)
        self.Tabs.addTab(self.assetLoaderTab, _fromUtf8(""))
        self.assetCreatorTab = QtGui.QWidget()
        self.assetCreatorTab.setObjectName(_fromUtf8("assetCreatorTab"))
        self.createAssetBtn = QtGui.QPushButton(self.assetCreatorTab)
        self.createAssetBtn.setGeometry(QtCore.QRect(420, 530, 221, 23))
        self.createAssetBtn.setObjectName(_fromUtf8("createAssetBtn"))
        self.departmentCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.departmentCreationList.setGeometry(QtCore.QRect(30, 80, 121, 192))
        self.departmentCreationList.setObjectName(_fromUtf8("departmentCreationList"))
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        self.softwareCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.softwareCreationList.setGeometry(QtCore.QRect(210, 70, 121, 192))
        self.softwareCreationList.setObjectName(_fromUtf8("softwareCreationList"))
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        self.assetNameCreationLineEdit = QtGui.QLineEdit(self.assetCreatorTab)
        self.assetNameCreationLineEdit.setGeometry(QtCore.QRect(370, 470, 113, 20))
        self.assetNameCreationLineEdit.setObjectName(_fromUtf8("assetNameCreationLineEdit"))
        self.assetNameCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.assetNameCreationLbl.setGeometry(QtCore.QRect(260, 470, 81, 16))
        self.assetNameCreationLbl.setObjectName(_fromUtf8("assetNameCreationLbl"))
        self.assetDependencyList = QtGui.QListWidget(self.assetCreatorTab)
        self.assetDependencyList.setEnabled(True)
        self.assetDependencyList.setGeometry(QtCore.QRect(720, 90, 256, 192))
        self.assetDependencyList.setObjectName(_fromUtf8("assetDependencyList"))
        self.seqCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.seqCreationList.setGeometry(QtCore.QRect(430, 90, 256, 192))
        self.seqCreationList.setObjectName(_fromUtf8("seqCreationList"))
        self.sequencesCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.sequencesCreationLbl.setGeometry(QtCore.QRect(450, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequencesCreationLbl.setFont(font)
        self.sequencesCreationLbl.setObjectName(_fromUtf8("sequencesCreationLbl"))
        self.dependencyCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.dependencyCreationLbl.setGeometry(QtCore.QRect(760, 60, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dependencyCreationLbl.setFont(font)
        self.dependencyCreationLbl.setObjectName(_fromUtf8("dependencyCreationLbl"))
        self.departmentCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.departmentCreationLbl.setGeometry(QtCore.QRect(40, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.departmentCreationLbl.setFont(font)
        self.departmentCreationLbl.setObjectName(_fromUtf8("departmentCreationLbl"))
        self.softwareCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.softwareCreationLbl.setGeometry(QtCore.QRect(220, 50, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.softwareCreationLbl.setFont(font)
        self.softwareCreationLbl.setObjectName(_fromUtf8("softwareCreationLbl"))
        self.webGroupBox = QtGui.QGroupBox(self.assetCreatorTab)
        self.webGroupBox.setEnabled(True)
        self.webGroupBox.setGeometry(QtCore.QRect(40, 290, 941, 80))
        self.webGroupBox.setFlat(False)
        self.webGroupBox.setCheckable(False)
        self.webGroupBox.setObjectName(_fromUtf8("webGroupBox"))
        self.conceptWebLineEdit = QtGui.QLineEdit(self.webGroupBox)
        self.conceptWebLineEdit.setEnabled(False)
        self.conceptWebLineEdit.setGeometry(QtCore.QRect(40, 30, 811, 20))
        self.conceptWebLineEdit.setObjectName(_fromUtf8("conceptWebLineEdit"))
        self.Tabs.addTab(self.assetCreatorTab, _fromUtf8(""))
        self.preferencesTab = QtGui.QWidget()
        self.preferencesTab.setObjectName(_fromUtf8("preferencesTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.preferencesTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.softwarePathGrpBox = QtGui.QGroupBox(self.preferencesTab)
        self.softwarePathGrpBox.setObjectName(_fromUtf8("softwarePathGrpBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.softwarePathGrpBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.photoshopPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.photoshopPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.photoshopPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.photoshopPathFrame.setObjectName(_fromUtf8("photoshopPathFrame"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.photoshopPathFrame)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.photoshopPrefLbl = QtGui.QLabel(self.photoshopPathFrame)
        self.photoshopPrefLbl.setObjectName(_fromUtf8("photoshopPrefLbl"))
        self.horizontalLayout_7.addWidget(self.photoshopPrefLbl)
        self.photoshopPathLineEdit = QtGui.QLineEdit(self.photoshopPathFrame)
        self.photoshopPathLineEdit.setText(_fromUtf8(""))
        self.photoshopPathLineEdit.setObjectName(_fromUtf8("photoshopPathLineEdit"))
        self.horizontalLayout_7.addWidget(self.photoshopPathLineEdit)
        self.verticalLayout_6.addWidget(self.photoshopPathFrame)
        self.mayaPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.mayaPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mayaPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mayaPathFrame.setObjectName(_fromUtf8("mayaPathFrame"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.mayaPathFrame)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mayaPrefLbl = QtGui.QLabel(self.mayaPathFrame)
        self.mayaPrefLbl.setObjectName(_fromUtf8("mayaPrefLbl"))
        self.horizontalLayout_8.addWidget(self.mayaPrefLbl)
        self.mayaPathLineEdit = QtGui.QLineEdit(self.mayaPathFrame)
        self.mayaPathLineEdit.setText(_fromUtf8(""))
        self.mayaPathLineEdit.setObjectName(_fromUtf8("mayaPathLineEdit"))
        self.horizontalLayout_8.addWidget(self.mayaPathLineEdit)
        self.verticalLayout_6.addWidget(self.mayaPathFrame)
        self.softimagePathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.softimagePathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.softimagePathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.softimagePathFrame.setObjectName(_fromUtf8("softimagePathFrame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.softimagePathFrame)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.softimagePrefLbl = QtGui.QLabel(self.softimagePathFrame)
        self.softimagePrefLbl.setObjectName(_fromUtf8("softimagePrefLbl"))
        self.horizontalLayout_9.addWidget(self.softimagePrefLbl)
        self.softimagePathLineEdit = QtGui.QLineEdit(self.softimagePathFrame)
        self.softimagePathLineEdit.setText(_fromUtf8(""))
        self.softimagePathLineEdit.setObjectName(_fromUtf8("softimagePathLineEdit"))
        self.horizontalLayout_9.addWidget(self.softimagePathLineEdit)
        self.verticalLayout_6.addWidget(self.softimagePathFrame)
        self.houdiniPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.houdiniPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.houdiniPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.houdiniPathFrame.setObjectName(_fromUtf8("houdiniPathFrame"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.houdiniPathFrame)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.houdiniPrefLbl = QtGui.QLabel(self.houdiniPathFrame)
        self.houdiniPrefLbl.setObjectName(_fromUtf8("houdiniPrefLbl"))
        self.horizontalLayout_10.addWidget(self.houdiniPrefLbl)
        self.houdiniPathLineEdit = QtGui.QLineEdit(self.houdiniPathFrame)
        self.houdiniPathLineEdit.setText(_fromUtf8(""))
        self.houdiniPathLineEdit.setObjectName(_fromUtf8("houdiniPathLineEdit"))
        self.horizontalLayout_10.addWidget(self.houdiniPathLineEdit)
        self.verticalLayout_6.addWidget(self.houdiniPathFrame)
        self.cinema4dPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.cinema4dPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cinema4dPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.cinema4dPathFrame.setObjectName(_fromUtf8("cinema4dPathFrame"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.cinema4dPathFrame)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cinema4dPrefLbl = QtGui.QLabel(self.cinema4dPathFrame)
        self.cinema4dPrefLbl.setObjectName(_fromUtf8("cinema4dPrefLbl"))
        self.horizontalLayout_11.addWidget(self.cinema4dPrefLbl)
        self.cinema4dPathLineEdit = QtGui.QLineEdit(self.cinema4dPathFrame)
        self.cinema4dPathLineEdit.setText(_fromUtf8(""))
        self.cinema4dPathLineEdit.setObjectName(_fromUtf8("cinema4dPathLineEdit"))
        self.horizontalLayout_11.addWidget(self.cinema4dPathLineEdit)
        self.verticalLayout_6.addWidget(self.cinema4dPathFrame)
        self.nukePathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.nukePathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nukePathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.nukePathFrame.setObjectName(_fromUtf8("nukePathFrame"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.nukePathFrame)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.nukePrefLbl = QtGui.QLabel(self.nukePathFrame)
        self.nukePrefLbl.setObjectName(_fromUtf8("nukePrefLbl"))
        self.horizontalLayout_12.addWidget(self.nukePrefLbl)
        self.nukePathLineEdit = QtGui.QLineEdit(self.nukePathFrame)
        self.nukePathLineEdit.setText(_fromUtf8(""))
        self.nukePathLineEdit.setObjectName(_fromUtf8("nukePathLineEdit"))
        self.horizontalLayout_12.addWidget(self.nukePathLineEdit)
        self.verticalLayout_6.addWidget(self.nukePathFrame)
        self.zbrushPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.zbrushPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.zbrushPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.zbrushPathFrame.setObjectName(_fromUtf8("zbrushPathFrame"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.zbrushPathFrame)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.zbrushPrefLbl = QtGui.QLabel(self.zbrushPathFrame)
        self.zbrushPrefLbl.setObjectName(_fromUtf8("zbrushPrefLbl"))
        self.horizontalLayout_19.addWidget(self.zbrushPrefLbl)
        self.zbrushPathLineEdit = QtGui.QLineEdit(self.zbrushPathFrame)
        self.zbrushPathLineEdit.setText(_fromUtf8(""))
        self.zbrushPathLineEdit.setObjectName(_fromUtf8("zbrushPathLineEdit"))
        self.horizontalLayout_19.addWidget(self.zbrushPathLineEdit)
        self.verticalLayout_6.addWidget(self.zbrushPathFrame)
        self.mariPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.mariPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mariPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mariPathFrame.setObjectName(_fromUtf8("mariPathFrame"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.mariPathFrame)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.mariPrefLbl = QtGui.QLabel(self.mariPathFrame)
        self.mariPrefLbl.setObjectName(_fromUtf8("mariPrefLbl"))
        self.horizontalLayout_21.addWidget(self.mariPrefLbl)
        self.mariPathLineEdit = QtGui.QLineEdit(self.mariPathFrame)
        self.mariPathLineEdit.setText(_fromUtf8(""))
        self.mariPathLineEdit.setObjectName(_fromUtf8("mariPathLineEdit"))
        self.horizontalLayout_21.addWidget(self.mariPathLineEdit)
        self.verticalLayout_6.addWidget(self.mariPathFrame)
        self.blenderPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.blenderPathFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.blenderPathFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.blenderPathFrame.setObjectName(_fromUtf8("blenderPathFrame"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.blenderPathFrame)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.blenderPrefLbl = QtGui.QLabel(self.blenderPathFrame)
        self.blenderPrefLbl.setObjectName(_fromUtf8("blenderPrefLbl"))
        self.horizontalLayout_22.addWidget(self.blenderPrefLbl)
        self.blenderPathLineEdit = QtGui.QLineEdit(self.blenderPathFrame)
        self.blenderPathLineEdit.setText(_fromUtf8(""))
        self.blenderPathLineEdit.setObjectName(_fromUtf8("blenderPathLineEdit"))
        self.horizontalLayout_22.addWidget(self.blenderPathLineEdit)
        self.verticalLayout_6.addWidget(self.blenderPathFrame)
        self.verticalLayout_7.addWidget(self.softwarePathGrpBox)
        self.savePrefBtn = QtGui.QPushButton(self.preferencesTab)
        self.savePrefBtn.setObjectName(_fromUtf8("savePrefBtn"))
        self.verticalLayout_7.addWidget(self.savePrefBtn)
        self.Tabs.addTab(self.preferencesTab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.Tabs)
        self.horizontalLayout_3.addWidget(self.assetManagerFrame)

        self.retranslateUi(Form)
        self.Tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        return Form

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Asset Manager", None))
        self.departmentList.setSortingEnabled(True)
        self.filterLbl_3.setText(_translate("Form", "Sequence", None))
        self.projectList.setSortingEnabled(True)
        self.filterLbl_4.setText(_translate("Form", "Asset", None))
        self.assetList.setSortingEnabled(True)
        self.seqList.setSortingEnabled(True)
        self.filterLbl_2.setText(_translate("Form", "Department", None))
        self.filterLbl.setText(_translate("Form", "Project", None))
        self.assetFilterClearBtn.setText(_translate("Form", "x", None))
        self.assetFilter.setPlaceholderText(_translate("Form", "filter", None))
        self.seqFilterClearBtn.setText(_translate("Form", "x", None))
        self.seqFilter.setPlaceholderText(_translate("Form", "filter", None))
        self.assetInfoGrp.setTitle(_translate("Form", "Info", None))
        self.label_3.setText(_translate("Form", "Thumbnail", None))
        self.updateThumbBtn.setText(_translate("Form", "Update Thumbnail", None))
        self.label_2.setText(_translate("Form", "Path on disk: ", None))
        self.assetPathLbl.setText(_translate("Form", "...", None))
        self.openInExplorerBtn.setText(_translate("Form", "Open in Explorer", None))
        self.label_5.setText(_translate("Form", "File Type:", None))
        self.fileTypeLbl.setText(_translate("Form", "...", None))
        self.label.setText(_translate("Form", "Comments:", None))
        self.addCommentBtn.setText(_translate("Form", "Add comment", None))
        self.actionGrpBox.setTitle(_translate("Form", "Action", None))
        self.createVersionBtn.setText(_translate("Form", "Create version", None))
        self.publishBtn.setText(_translate("Form", "Publish", None))
        self.loadBtn.setText(_translate("Form", "Load Asset", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.assetLoaderTab), _translate("Form", "Asset Loader", None))
        self.createAssetBtn.setText(_translate("Form", "Create Asset", None))
        self.departmentCreationList.setSortingEnabled(True)
        __sortingEnabled = self.departmentCreationList.isSortingEnabled()
        self.departmentCreationList.setSortingEnabled(False)
        item = self.departmentCreationList.item(0)
        item.setText(_translate("Form", "Concept", None))
        item = self.departmentCreationList.item(1)
        item.setText(_translate("Form", "Layout", None))
        item = self.departmentCreationList.item(2)
        item.setText(_translate("Form", "Modeling", None))
        self.departmentCreationList.setSortingEnabled(__sortingEnabled)
        self.softwareCreationList.setSortingEnabled(True)
        __sortingEnabled = self.softwareCreationList.isSortingEnabled()
        self.softwareCreationList.setSortingEnabled(False)
        item = self.softwareCreationList.item(0)
        item.setText(_translate("Form", "Blender", None))
        item = self.softwareCreationList.item(1)
        item.setText(_translate("Form", "Cinema 4D", None))
        item = self.softwareCreationList.item(2)
        item.setText(_translate("Form", "Houdini", None))
        item = self.softwareCreationList.item(3)
        item.setText(_translate("Form", "Maya", None))
        item = self.softwareCreationList.item(4)
        item.setText(_translate("Form", "Photoshop", None))
        item = self.softwareCreationList.item(5)
        item.setText(_translate("Form", "Softimage", None))
        item = self.softwareCreationList.item(6)
        item.setText(_translate("Form", "ZBrush", None))
        self.softwareCreationList.setSortingEnabled(__sortingEnabled)
        self.assetNameCreationLineEdit.setPlaceholderText(_translate("Form", "ex: mainchar, house...", None))
        self.assetNameCreationLbl.setText(_translate("Form", "Asset name:", None))
        self.assetDependencyList.setSortingEnabled(True)
        self.seqCreationList.setSortingEnabled(True)
        self.sequencesCreationLbl.setText(_translate("Form", "Sequences", None))
        self.dependencyCreationLbl.setText(_translate("Form", "Dependency", None))
        self.departmentCreationLbl.setText(_translate("Form", "Departments", None))
        self.softwareCreationLbl.setText(_translate("Form", "Software", None))
        self.webGroupBox.setTitle(_translate("Form", "URL", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.assetCreatorTab), _translate("Form", "Asset Creator", None))
        self.softwarePathGrpBox.setTitle(_translate("Form", "Software Paths", None))
        self.photoshopPrefLbl.setText(_translate("Form", "Photoshop", None))
        self.photoshopPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.mayaPrefLbl.setText(_translate("Form", "Maya", None))
        self.mayaPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.softimagePrefLbl.setText(_translate("Form", "Softimage", None))
        self.softimagePathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.houdiniPrefLbl.setText(_translate("Form", "Houdini", None))
        self.houdiniPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.cinema4dPrefLbl.setText(_translate("Form", "Cinema 4D", None))
        self.cinema4dPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.nukePrefLbl.setText(_translate("Form", "Nuke", None))
        self.nukePathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.zbrushPrefLbl.setText(_translate("Form", "ZBrush", None))
        self.zbrushPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.mariPrefLbl.setText(_translate("Form", "Mari", None))
        self.mariPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.blenderPrefLbl.setText(_translate("Form", "Blender", None))
        self.blenderPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.savePrefBtn.setText(_translate("Form", "Save Preferences", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.preferencesTab), _translate("Form", "Preferences", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

