# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\01-NAD\_pipeline\_utilities\_asset_manager\media\main_window.ui'
#
# Created: Wed Jul 08 16:09:32 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1083, 910)
        Form.setMinimumSize(QtCore.QSize(1050, 600))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Form.setMouseTracking(False)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet(_fromUtf8(""))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.assetManagerFrame = QtGui.QFrame(Form)
        self.assetManagerFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.assetManagerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.assetManagerFrame.setObjectName(_fromUtf8("assetManagerFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.assetManagerFrame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Tabs = QtGui.QTabWidget(self.assetManagerFrame)
        self.Tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.Tabs.setElideMode(QtCore.Qt.ElideNone)
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.assetLoaderTab = QtGui.QWidget()
        self.assetLoaderTab.setObjectName(_fromUtf8("assetLoaderTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.assetLoaderTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.filterGroupBox = QtGui.QGroupBox(self.assetLoaderTab)
        self.filterGroupBox.setFlat(True)
        self.filterGroupBox.setCheckable(False)
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.filterGroupBox)
        self.verticalLayout_9.setMargin(5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.assignedToFilterLbl = QtGui.QLabel(self.filterGroupBox)
        self.assignedToFilterLbl.setObjectName(_fromUtf8("assignedToFilterLbl"))
        self.verticalLayout_9.addWidget(self.assignedToFilterLbl)
        self.meOnlyFrame = QtGui.QFrame(self.filterGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.meOnlyFrame.setFont(font)
        self.meOnlyFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.meOnlyFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.meOnlyFrame.setObjectName(_fromUtf8("meOnlyFrame"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.meOnlyFrame)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.assignedToFilterComboBox = QtGui.QComboBox(self.meOnlyFrame)
        self.assignedToFilterComboBox.setFrame(True)
        self.assignedToFilterComboBox.setObjectName(_fromUtf8("assignedToFilterComboBox"))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.assignedToFilterComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.assignedToFilterComboBox)
        self.meOnlyCheckBox = QtGui.QCheckBox(self.meOnlyFrame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.meOnlyCheckBox.setFont(font)
        self.meOnlyCheckBox.setChecked(False)
        self.meOnlyCheckBox.setTristate(False)
        self.meOnlyCheckBox.setObjectName(_fromUtf8("meOnlyCheckBox"))
        self.horizontalLayout_16.addWidget(self.meOnlyCheckBox)
        self.verticalLayout_9.addWidget(self.meOnlyFrame)
        self.verticalLayout_2.addWidget(self.filterGroupBox)
        self.line_2 = QtGui.QFrame(self.assetLoaderTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.listsFrame = QtGui.QFrame(self.assetLoaderTab)
        self.listsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.listsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.listsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.listsFrame.setObjectName(_fromUtf8("listsFrame"))
        self.gridLayout = QtGui.QGridLayout(self.listsFrame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addProjectFrame = QtGui.QFrame(self.listsFrame)
        self.addProjectFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addProjectFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addProjectFrame.setObjectName(_fromUtf8("addProjectFrame"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.addProjectFrame)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.addProjectLineEdit = QtGui.QLineEdit(self.addProjectFrame)
        self.addProjectLineEdit.setObjectName(_fromUtf8("addProjectLineEdit"))
        self.horizontalLayout_14.addWidget(self.addProjectLineEdit)
        self.projectShortnameLineEdit = QtGui.QLineEdit(self.addProjectFrame)
        self.projectShortnameLineEdit.setObjectName(_fromUtf8("projectShortnameLineEdit"))
        self.horizontalLayout_14.addWidget(self.projectShortnameLineEdit)
        self.addProjectBtn = QtGui.QPushButton(self.addProjectFrame)
        self.addProjectBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.addProjectBtn.setObjectName(_fromUtf8("addProjectBtn"))
        self.horizontalLayout_14.addWidget(self.addProjectBtn)
        self.gridLayout.addWidget(self.addProjectFrame, 4, 0, 1, 1)
        self.seqFilterFrame = QtGui.QFrame(self.listsFrame)
        self.seqFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.seqFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.seqFilterFrame.setObjectName(_fromUtf8("seqFilterFrame"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.seqFilterFrame)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.seqFilter = QtGui.QLineEdit(self.seqFilterFrame)
        self.seqFilter.setObjectName(_fromUtf8("seqFilter"))
        self.horizontalLayout_6.addWidget(self.seqFilter)
        self.seqFilterClearBtn = QtGui.QPushButton(self.seqFilterFrame)
        self.seqFilterClearBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.seqFilterClearBtn.setIconSize(QtCore.QSize(16, 16))
        self.seqFilterClearBtn.setCheckable(False)
        self.seqFilterClearBtn.setDefault(False)
        self.seqFilterClearBtn.setFlat(False)
        self.seqFilterClearBtn.setObjectName(_fromUtf8("seqFilterClearBtn"))
        self.horizontalLayout_6.addWidget(self.seqFilterClearBtn)
        self.gridLayout.addWidget(self.seqFilterFrame, 2, 1, 1, 1)
        self.assetFilterFrame = QtGui.QFrame(self.listsFrame)
        self.assetFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.assetFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.assetFilterFrame.setLineWidth(1)
        self.assetFilterFrame.setObjectName(_fromUtf8("assetFilterFrame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.assetFilterFrame)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.assetFilter = QtGui.QLineEdit(self.assetFilterFrame)
        self.assetFilter.setObjectName(_fromUtf8("assetFilter"))
        self.horizontalLayout_5.addWidget(self.assetFilter)
        self.assetFilterClearBtn = QtGui.QPushButton(self.assetFilterFrame)
        self.assetFilterClearBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.assetFilterClearBtn.setObjectName(_fromUtf8("assetFilterClearBtn"))
        self.horizontalLayout_5.addWidget(self.assetFilterClearBtn)
        self.gridLayout.addWidget(self.assetFilterFrame, 2, 6, 1, 1)
        self.departmentList = QtGui.QListWidget(self.listsFrame)
        self.departmentList.setFrameShape(QtGui.QFrame.Box)
        self.departmentList.setObjectName(_fromUtf8("departmentList"))
        self.gridLayout.addWidget(self.departmentList, 3, 3, 1, 1)
        self.projectList = QtGui.QListWidget(self.listsFrame)
        self.projectList.setFrameShape(QtGui.QFrame.Box)
        self.projectList.setObjectName(_fromUtf8("projectList"))
        self.gridLayout.addWidget(self.projectList, 3, 0, 1, 1)
        self.assetLbl = QtGui.QLabel(self.listsFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.assetLbl.setFont(font)
        self.assetLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.assetLbl.setLineWidth(0)
        self.assetLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.assetLbl.setObjectName(_fromUtf8("assetLbl"))
        self.gridLayout.addWidget(self.assetLbl, 0, 6, 1, 1)
        self.assetList = QtGui.QListWidget(self.listsFrame)
        self.assetList.setFrameShape(QtGui.QFrame.Box)
        self.assetList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assetList.setObjectName(_fromUtf8("assetList"))
        self.gridLayout.addWidget(self.assetList, 3, 6, 1, 1)
        self.departmentLbl = QtGui.QLabel(self.listsFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.departmentLbl.setFont(font)
        self.departmentLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.departmentLbl.setLineWidth(0)
        self.departmentLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.departmentLbl.setObjectName(_fromUtf8("departmentLbl"))
        self.gridLayout.addWidget(self.departmentLbl, 0, 3, 1, 1)
        self.projectLbl = QtGui.QLabel(self.listsFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.projectLbl.setFont(font)
        self.projectLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.projectLbl.setLineWidth(0)
        self.projectLbl.setTextFormat(QtCore.Qt.AutoText)
        self.projectLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.projectLbl.setObjectName(_fromUtf8("projectLbl"))
        self.gridLayout.addWidget(self.projectLbl, 0, 0, 1, 1)
        self.shotList = QtGui.QListWidget(self.listsFrame)
        self.shotList.setFrameShape(QtGui.QFrame.Box)
        self.shotList.setObjectName(_fromUtf8("shotList"))
        self.gridLayout.addWidget(self.shotList, 3, 2, 1, 1)
        self.seqList = QtGui.QListWidget(self.listsFrame)
        self.seqList.setFrameShape(QtGui.QFrame.Box)
        self.seqList.setObjectName(_fromUtf8("seqList"))
        self.gridLayout.addWidget(self.seqList, 3, 1, 1, 1)
        self.seqLbl = QtGui.QLabel(self.listsFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.seqLbl.setFont(font)
        self.seqLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.seqLbl.setLineWidth(0)
        self.seqLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.seqLbl.setObjectName(_fromUtf8("seqLbl"))
        self.gridLayout.addWidget(self.seqLbl, 0, 1, 1, 1)
        self.shotLbl = QtGui.QLabel(self.listsFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shotLbl.setFont(font)
        self.shotLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.shotLbl.setLineWidth(0)
        self.shotLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.shotLbl.setObjectName(_fromUtf8("shotLbl"))
        self.gridLayout.addWidget(self.shotLbl, 0, 2, 1, 1)
        self.versionList = QtGui.QListWidget(self.listsFrame)
        self.versionList.setFrameShape(QtGui.QFrame.Box)
        self.versionList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.versionList.setObjectName(_fromUtf8("versionList"))
        self.gridLayout.addWidget(self.versionList, 3, 7, 1, 1)
        self.versionLbl = QtGui.QLabel(self.listsFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.versionLbl.setFont(font)
        self.versionLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.versionLbl.setLineWidth(0)
        self.versionLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLbl.setObjectName(_fromUtf8("versionLbl"))
        self.gridLayout.addWidget(self.versionLbl, 0, 7, 1, 1)
        self.addSequenceFrame = QtGui.QFrame(self.listsFrame)
        self.addSequenceFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addSequenceFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addSequenceFrame.setObjectName(_fromUtf8("addSequenceFrame"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.addSequenceFrame)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.addSequenceLineEdit = QtGui.QLineEdit(self.addSequenceFrame)
        self.addSequenceLineEdit.setMaxLength(3)
        self.addSequenceLineEdit.setObjectName(_fromUtf8("addSequenceLineEdit"))
        self.horizontalLayout_13.addWidget(self.addSequenceLineEdit)
        self.addSequenceBtn = QtGui.QPushButton(self.addSequenceFrame)
        self.addSequenceBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.addSequenceBtn.setObjectName(_fromUtf8("addSequenceBtn"))
        self.horizontalLayout_13.addWidget(self.addSequenceBtn)
        self.gridLayout.addWidget(self.addSequenceFrame, 4, 1, 1, 1)
        self.addShotFrame = QtGui.QFrame(self.listsFrame)
        self.addShotFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addShotFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addShotFrame.setObjectName(_fromUtf8("addShotFrame"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.addShotFrame)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.shotSpinBox = QtGui.QSpinBox(self.addShotFrame)
        self.shotSpinBox.setMaximum(9999)
        self.shotSpinBox.setSingleStep(10)
        self.shotSpinBox.setObjectName(_fromUtf8("shotSpinBox"))
        self.horizontalLayout_15.addWidget(self.shotSpinBox)
        self.addShotBtn = QtGui.QPushButton(self.addShotFrame)
        self.addShotBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.addShotBtn.setObjectName(_fromUtf8("addShotBtn"))
        self.horizontalLayout_15.addWidget(self.addShotBtn)
        self.gridLayout.addWidget(self.addShotFrame, 4, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.listsFrame)
        self.infoFrame = QtGui.QFrame(self.assetLoaderTab)
        self.infoFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.infoFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.infoFrame.setObjectName(_fromUtf8("infoFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.infoFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.assetInfoGrp = QtGui.QGroupBox(self.infoFrame)
        self.assetInfoGrp.setAutoFillBackground(False)
        self.assetInfoGrp.setFlat(True)
        self.assetInfoGrp.setCheckable(False)
        self.assetInfoGrp.setObjectName(_fromUtf8("assetInfoGrp"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.assetInfoGrp)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.thumbnailFrame = QtGui.QFrame(self.assetInfoGrp)
        self.thumbnailFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.thumbnailFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.thumbnailFrame.setLineWidth(1)
        self.thumbnailFrame.setMidLineWidth(0)
        self.thumbnailFrame.setObjectName(_fromUtf8("thumbnailFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.thumbnailFrame)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.fileTypeFrame = QtGui.QFrame(self.thumbnailFrame)
        self.fileTypeFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.fileTypeFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fileTypeFrame.setObjectName(_fromUtf8("fileTypeFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.fileTypeFrame)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fileTypeLbl = QtGui.QLabel(self.fileTypeFrame)
        self.fileTypeLbl.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fileTypeLbl.setFont(font)
        self.fileTypeLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.fileTypeLbl.setLineWidth(0)
        self.fileTypeLbl.setObjectName(_fromUtf8("fileTypeLbl"))
        self.horizontalLayout_4.addWidget(self.fileTypeLbl)
        self.fileTypeValueLbl = QtGui.QLabel(self.fileTypeFrame)
        self.fileTypeValueLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.fileTypeValueLbl.setLineWidth(0)
        self.fileTypeValueLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fileTypeValueLbl.setObjectName(_fromUtf8("fileTypeValueLbl"))
        self.horizontalLayout_4.addWidget(self.fileTypeValueLbl)
        self.verticalLayout_4.addWidget(self.fileTypeFrame)
        self.thumbnailLbl = QtGui.QLabel(self.thumbnailFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thumbnailLbl.setFont(font)
        self.thumbnailLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.thumbnailLbl.setObjectName(_fromUtf8("thumbnailLbl"))
        self.verticalLayout_4.addWidget(self.thumbnailLbl)
        self.assetImg = QtGui.QLabel(self.thumbnailFrame)
        self.assetImg.setMinimumSize(QtCore.QSize(400, 200))
        self.assetImg.setMaximumSize(QtCore.QSize(1000, 200))
        self.assetImg.setAutoFillBackground(False)
        self.assetImg.setFrameShape(QtGui.QFrame.NoFrame)
        self.assetImg.setFrameShadow(QtGui.QFrame.Raised)
        self.assetImg.setLineWidth(1)
        self.assetImg.setText(_fromUtf8(""))
        self.assetImg.setTextFormat(QtCore.Qt.AutoText)
        self.assetImg.setScaledContents(False)
        self.assetImg.setAlignment(QtCore.Qt.AlignCenter)
        self.assetImg.setWordWrap(False)
        self.assetImg.setObjectName(_fromUtf8("assetImg"))
        self.verticalLayout_4.addWidget(self.assetImg)
        self.updateThumbBtn = QtGui.QPushButton(self.thumbnailFrame)
        self.updateThumbBtn.setObjectName(_fromUtf8("updateThumbBtn"))
        self.verticalLayout_4.addWidget(self.updateThumbBtn)
        self.openInExplorerBtn = QtGui.QPushButton(self.thumbnailFrame)
        self.openInExplorerBtn.setObjectName(_fromUtf8("openInExplorerBtn"))
        self.verticalLayout_4.addWidget(self.openInExplorerBtn)
        self.horizontalLayout.addWidget(self.thumbnailFrame)
        self.line = QtGui.QFrame(self.assetInfoGrp)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.assetInfoFrame = QtGui.QFrame(self.assetInfoGrp)
        self.assetInfoFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.assetInfoFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.assetInfoFrame.setObjectName(_fromUtf8("assetInfoFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.assetInfoFrame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.createdByFrame = QtGui.QFrame(self.assetInfoFrame)
        self.createdByFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.createdByFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.createdByFrame.setObjectName(_fromUtf8("createdByFrame"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.createdByFrame)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.createdByLbl = QtGui.QLabel(self.createdByFrame)
        self.createdByLbl.setMaximumSize(QtCore.QSize(64, 16777215))
        self.createdByLbl.setObjectName(_fromUtf8("createdByLbl"))
        self.horizontalLayout_17.addWidget(self.createdByLbl)
        self.createdByValueLbl = QtGui.QLabel(self.createdByFrame)
        self.createdByValueLbl.setObjectName(_fromUtf8("createdByValueLbl"))
        self.horizontalLayout_17.addWidget(self.createdByValueLbl)
        self.assignedToLbl = QtGui.QLabel(self.createdByFrame)
        self.assignedToLbl.setMaximumSize(QtCore.QSize(64, 16777215))
        self.assignedToLbl.setObjectName(_fromUtf8("assignedToLbl"))
        self.horizontalLayout_17.addWidget(self.assignedToLbl)
        self.assignedToValueLbl = QtGui.QLabel(self.createdByFrame)
        self.assignedToValueLbl.setObjectName(_fromUtf8("assignedToValueLbl"))
        self.horizontalLayout_17.addWidget(self.assignedToValueLbl)
        self.verticalLayout.addWidget(self.createdByFrame)
        self.assignedToFrame_2 = QtGui.QFrame(self.assetInfoFrame)
        self.assignedToFrame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.assignedToFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.assignedToFrame_2.setObjectName(_fromUtf8("assignedToFrame_2"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.assignedToFrame_2)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.dueDateLbl = QtGui.QLabel(self.assignedToFrame_2)
        self.dueDateLbl.setMaximumSize(QtCore.QSize(44, 16777215))
        self.dueDateLbl.setObjectName(_fromUtf8("dueDateLbl"))
        self.horizontalLayout_18.addWidget(self.dueDateLbl)
        self.dueDateValueLbl = QtGui.QLabel(self.assignedToFrame_2)
        self.dueDateValueLbl.setObjectName(_fromUtf8("dueDateValueLbl"))
        self.horizontalLayout_18.addWidget(self.dueDateValueLbl)
        self.timeLeftLbl = QtGui.QLabel(self.assignedToFrame_2)
        self.timeLeftLbl.setObjectName(_fromUtf8("timeLeftLbl"))
        self.horizontalLayout_18.addWidget(self.timeLeftLbl)
        self.verticalLayout.addWidget(self.assignedToFrame_2)
        self.stateFrame = QtGui.QFrame(self.assetInfoFrame)
        self.stateFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.stateFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.stateFrame.setObjectName(_fromUtf8("stateFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.stateFrame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.statusLbl = QtGui.QLabel(self.stateFrame)
        self.statusLbl.setMaximumSize(QtCore.QSize(40, 16777215))
        self.statusLbl.setObjectName(_fromUtf8("statusLbl"))
        self.horizontalLayout_2.addWidget(self.statusLbl)
        self.label = QtGui.QLabel(self.stateFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.stateFrame)
        self.stateFrame_2 = QtGui.QFrame(self.assetInfoFrame)
        self.stateFrame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.stateFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.stateFrame_2.setObjectName(_fromUtf8("stateFrame_2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.stateFrame_2)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.statusLbl_2 = QtGui.QLabel(self.stateFrame_2)
        self.statusLbl_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.statusLbl_2.setObjectName(_fromUtf8("statusLbl_2"))
        self.horizontalLayout_20.addWidget(self.statusLbl_2)
        self.label_2 = QtGui.QLabel(self.stateFrame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_20.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.stateFrame_2)
        self.commentsLbl = QtGui.QLabel(self.assetInfoFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.commentsLbl.setFont(font)
        self.commentsLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.commentsLbl.setObjectName(_fromUtf8("commentsLbl"))
        self.verticalLayout.addWidget(self.commentsLbl)
        self.commentTxt = QtGui.QTextEdit(self.assetInfoFrame)
        self.commentTxt.setFrameShape(QtGui.QFrame.Box)
        self.commentTxt.setReadOnly(True)
        self.commentTxt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.commentTxt.setObjectName(_fromUtf8("commentTxt"))
        self.verticalLayout.addWidget(self.commentTxt)
        self.commentTxtLine = QtGui.QLineEdit(self.assetInfoFrame)
        self.commentTxtLine.setObjectName(_fromUtf8("commentTxtLine"))
        self.verticalLayout.addWidget(self.commentTxtLine)
        self.addCommentBtn = QtGui.QPushButton(self.assetInfoFrame)
        self.addCommentBtn.setObjectName(_fromUtf8("addCommentBtn"))
        self.verticalLayout.addWidget(self.addCommentBtn)
        self.horizontalLayout.addWidget(self.assetInfoFrame)
        self.verticalLayout_3.addWidget(self.assetInfoGrp)
        self.actionGrpBox = QtGui.QGroupBox(self.infoFrame)
        self.actionGrpBox.setFlat(True)
        self.actionGrpBox.setObjectName(_fromUtf8("actionGrpBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.actionGrpBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.actionFrame = QtGui.QFrame(self.actionGrpBox)
        self.actionFrame.setFrameShape(QtGui.QFrame.Box)
        self.actionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.actionFrame.setObjectName(_fromUtf8("actionFrame"))
        self.actionFrameLayout = QtGui.QVBoxLayout(self.actionFrame)
        self.actionFrameLayout.setObjectName(_fromUtf8("actionFrameLayout"))
        self.verticalLayout_8.addWidget(self.actionFrame)
        self.verticalLayout_3.addWidget(self.actionGrpBox)
        self.verticalLayout_2.addWidget(self.infoFrame)
        self.createVersionBtn = QtGui.QPushButton(self.assetLoaderTab)
        self.createVersionBtn.setObjectName(_fromUtf8("createVersionBtn"))
        self.verticalLayout_2.addWidget(self.createVersionBtn)
        self.publishBtn = QtGui.QPushButton(self.assetLoaderTab)
        self.publishBtn.setObjectName(_fromUtf8("publishBtn"))
        self.verticalLayout_2.addWidget(self.publishBtn)
        self.loadBtn = QtGui.QPushButton(self.assetLoaderTab)
        self.loadBtn.setObjectName(_fromUtf8("loadBtn"))
        self.verticalLayout_2.addWidget(self.loadBtn)
        self.Tabs.addTab(self.assetLoaderTab, _fromUtf8(""))
        self.tmTab = QtGui.QWidget()
        self.tmTab.setObjectName(_fromUtf8("tmTab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tmTab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tmMainFrame = QtGui.QFrame(self.tmTab)
        self.tmMainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tmMainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmMainFrame.setObjectName(_fromUtf8("tmMainFrame"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.tmMainFrame)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.tmFilterByGroupBox = QtGui.QGroupBox(self.tmMainFrame)
        self.tmFilterByGroupBox.setFlat(True)
        self.tmFilterByGroupBox.setCheckable(False)
        self.tmFilterByGroupBox.setObjectName(_fromUtf8("tmFilterByGroupBox"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.tmFilterByGroupBox)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.tmProjectFilterFrame = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmProjectFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmProjectFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmProjectFilterFrame.setObjectName(_fromUtf8("tmProjectFilterFrame"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout(self.tmProjectFilterFrame)
        self.horizontalLayout_35.setMargin(0)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.tmProjectLbl = QtGui.QLabel(self.tmProjectFilterFrame)
        self.tmProjectLbl.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmProjectLbl.setObjectName(_fromUtf8("tmProjectLbl"))
        self.horizontalLayout_35.addWidget(self.tmProjectLbl)
        self.tmFilterByProjectComboBox = QtGui.QComboBox(self.tmProjectFilterFrame)
        self.tmFilterByProjectComboBox.setObjectName(_fromUtf8("tmFilterByProjectComboBox"))
        self.horizontalLayout_35.addWidget(self.tmFilterByProjectComboBox)
        self.verticalLayout_26.addWidget(self.tmProjectFilterFrame)
        self.tmSequenceFilterFrame = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmSequenceFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmSequenceFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmSequenceFilterFrame.setObjectName(_fromUtf8("tmSequenceFilterFrame"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.tmSequenceFilterFrame)
        self.horizontalLayout_36.setMargin(0)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.tmSequenceLbl = QtGui.QLabel(self.tmSequenceFilterFrame)
        self.tmSequenceLbl.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmSequenceLbl.setObjectName(_fromUtf8("tmSequenceLbl"))
        self.horizontalLayout_36.addWidget(self.tmSequenceLbl)
        self.tmFilterBySequenceComboBox = QtGui.QComboBox(self.tmSequenceFilterFrame)
        self.tmFilterBySequenceComboBox.setObjectName(_fromUtf8("tmFilterBySequenceComboBox"))
        self.horizontalLayout_36.addWidget(self.tmFilterBySequenceComboBox)
        self.verticalLayout_26.addWidget(self.tmSequenceFilterFrame)
        self.tmShotFilterFrame = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmShotFilterFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tmShotFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmShotFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmShotFilterFrame.setObjectName(_fromUtf8("tmShotFilterFrame"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.tmShotFilterFrame)
        self.horizontalLayout_37.setMargin(0)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.tmShotLbl = QtGui.QLabel(self.tmShotFilterFrame)
        self.tmShotLbl.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmShotLbl.setObjectName(_fromUtf8("tmShotLbl"))
        self.horizontalLayout_37.addWidget(self.tmShotLbl)
        self.tmFilterByShotComboBox = QtGui.QComboBox(self.tmShotFilterFrame)
        self.tmFilterByShotComboBox.setObjectName(_fromUtf8("tmFilterByShotComboBox"))
        self.horizontalLayout_37.addWidget(self.tmFilterByShotComboBox)
        self.verticalLayout_26.addWidget(self.tmShotFilterFrame)
        self.tmDepartmentFilterFrame = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmDepartmentFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmDepartmentFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmDepartmentFilterFrame.setObjectName(_fromUtf8("tmDepartmentFilterFrame"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tmDepartmentFilterFrame)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.tmDepartmentFilter = QtGui.QLabel(self.tmDepartmentFilterFrame)
        self.tmDepartmentFilter.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmDepartmentFilter.setObjectName(_fromUtf8("tmDepartmentFilter"))
        self.horizontalLayout_29.addWidget(self.tmDepartmentFilter)
        self.tmFilterByDeptComboBox = QtGui.QComboBox(self.tmDepartmentFilterFrame)
        self.tmFilterByDeptComboBox.setFrame(True)
        self.tmFilterByDeptComboBox.setObjectName(_fromUtf8("tmFilterByDeptComboBox"))
        self.horizontalLayout_29.addWidget(self.tmFilterByDeptComboBox)
        self.verticalLayout_26.addWidget(self.tmDepartmentFilterFrame)
        self.tmStatusFilterGroupBox = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmStatusFilterGroupBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmStatusFilterGroupBox.setFrameShadow(QtGui.QFrame.Raised)
        self.tmStatusFilterGroupBox.setObjectName(_fromUtf8("tmStatusFilterGroupBox"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.tmStatusFilterGroupBox)
        self.horizontalLayout_30.setMargin(0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.tmStatusLbl = QtGui.QLabel(self.tmStatusFilterGroupBox)
        self.tmStatusLbl.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmStatusLbl.setObjectName(_fromUtf8("tmStatusLbl"))
        self.horizontalLayout_30.addWidget(self.tmStatusLbl)
        self.tmFilterByStatusComboBox = QtGui.QComboBox(self.tmStatusFilterGroupBox)
        self.tmFilterByStatusComboBox.setFrame(True)
        self.tmFilterByStatusComboBox.setObjectName(_fromUtf8("tmFilterByStatusComboBox"))
        self.horizontalLayout_30.addWidget(self.tmFilterByStatusComboBox)
        self.verticalLayout_26.addWidget(self.tmStatusFilterGroupBox)
        self.tmFilterByMemberFrame = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmFilterByMemberFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmFilterByMemberFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmFilterByMemberFrame.setObjectName(_fromUtf8("tmFilterByMemberFrame"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.tmFilterByMemberFrame)
        self.horizontalLayout_31.setMargin(0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.tmMemberLbl = QtGui.QLabel(self.tmFilterByMemberFrame)
        self.tmMemberLbl.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmMemberLbl.setObjectName(_fromUtf8("tmMemberLbl"))
        self.horizontalLayout_31.addWidget(self.tmMemberLbl)
        self.tmFilterByMemberComboBox = QtGui.QComboBox(self.tmFilterByMemberFrame)
        self.tmFilterByMemberComboBox.setFrame(True)
        self.tmFilterByMemberComboBox.setObjectName(_fromUtf8("tmFilterByMemberComboBox"))
        self.horizontalLayout_31.addWidget(self.tmFilterByMemberComboBox)
        self.verticalLayout_26.addWidget(self.tmFilterByMemberFrame)
        self.tmBidFilterFrame = QtGui.QFrame(self.tmFilterByGroupBox)
        self.tmBidFilterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tmBidFilterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tmBidFilterFrame.setObjectName(_fromUtf8("tmBidFilterFrame"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.tmBidFilterFrame)
        self.horizontalLayout_33.setMargin(0)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.tmBidLbl = QtGui.QLabel(self.tmBidFilterFrame)
        self.tmBidLbl.setMinimumSize(QtCore.QSize(65, 0))
        self.tmBidLbl.setMaximumSize(QtCore.QSize(60, 16777215))
        self.tmBidLbl.setObjectName(_fromUtf8("tmBidLbl"))
        self.horizontalLayout_33.addWidget(self.tmBidLbl)
        self.tmBidOperationComboBox = QtGui.QComboBox(self.tmBidFilterFrame)
        self.tmBidOperationComboBox.setMinimumSize(QtCore.QSize(41, 0))
        self.tmBidOperationComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.tmBidOperationComboBox.setFrame(True)
        self.tmBidOperationComboBox.setObjectName(_fromUtf8("tmBidOperationComboBox"))
        self.tmBidOperationComboBox.addItem(_fromUtf8(""))
        self.tmBidOperationComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_33.addWidget(self.tmBidOperationComboBox)
        self.tmFilterByBidComboBox = QtGui.QSpinBox(self.tmBidFilterFrame)
        self.tmFilterByBidComboBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.tmFilterByBidComboBox.setObjectName(_fromUtf8("tmFilterByBidComboBox"))
        self.horizontalLayout_33.addWidget(self.tmFilterByBidComboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem)
        self.verticalLayout_26.addWidget(self.tmBidFilterFrame)
        self.verticalLayout_27.addWidget(self.tmFilterByGroupBox)
        self.tmTaskManagementFrame = QtGui.QGroupBox(self.tmMainFrame)
        self.tmTaskManagementFrame.setFlat(True)
        self.tmTaskManagementFrame.setObjectName(_fromUtf8("tmTaskManagementFrame"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.tmTaskManagementFrame)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.tmNbrOfRowsToAddSpinBox = QtGui.QSpinBox(self.tmTaskManagementFrame)
        self.tmNbrOfRowsToAddSpinBox.setWrapping(False)
        self.tmNbrOfRowsToAddSpinBox.setFrame(False)
        self.tmNbrOfRowsToAddSpinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tmNbrOfRowsToAddSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.tmNbrOfRowsToAddSpinBox.setMinimum(1)
        self.tmNbrOfRowsToAddSpinBox.setMaximum(100)
        self.tmNbrOfRowsToAddSpinBox.setProperty("value", 1)
        self.tmNbrOfRowsToAddSpinBox.setObjectName(_fromUtf8("tmNbrOfRowsToAddSpinBox"))
        self.horizontalLayout_32.addWidget(self.tmNbrOfRowsToAddSpinBox)
        self.tmAddTaskBtn = QtGui.QPushButton(self.tmTaskManagementFrame)
        self.tmAddTaskBtn.setObjectName(_fromUtf8("tmAddTaskBtn"))
        self.horizontalLayout_32.addWidget(self.tmAddTaskBtn)
        self.tmCompleteTaskBtn = QtGui.QPushButton(self.tmTaskManagementFrame)
        self.tmCompleteTaskBtn.setObjectName(_fromUtf8("tmCompleteTaskBtn"))
        self.horizontalLayout_32.addWidget(self.tmCompleteTaskBtn)
        self.tmRemoveTaskBtn = QtGui.QPushButton(self.tmTaskManagementFrame)
        self.tmRemoveTaskBtn.setObjectName(_fromUtf8("tmRemoveTaskBtn"))
        self.horizontalLayout_32.addWidget(self.tmRemoveTaskBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem1)
        self.verticalLayout_27.addWidget(self.tmTaskManagementFrame)
        self.tmTableWidget = QtGui.QTableWidget(self.tmMainFrame)
        self.tmTableWidget.setShowGrid(False)
        self.tmTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tmTableWidget.setObjectName(_fromUtf8("tmTableWidget"))
        self.tmTableWidget.setColumnCount(11)
        self.tmTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tmTableWidget.setHorizontalHeaderItem(10, item)
        self.tmTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tmTableWidget.horizontalHeader().setStretchLastSection(True)
        self.tmTableWidget.verticalHeader().setVisible(False)
        self.tmTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_27.addWidget(self.tmTableWidget)
        self.verticalLayout_11.addWidget(self.tmMainFrame)
        self.Tabs.addTab(self.tmTab, _fromUtf8(""))
        self.myTasksTab = QtGui.QWidget()
        self.myTasksTab.setObjectName(_fromUtf8("myTasksTab"))
        self.Tabs.addTab(self.myTasksTab, _fromUtf8(""))
        self.assetCreatorTab = QtGui.QWidget()
        self.assetCreatorTab.setObjectName(_fromUtf8("assetCreatorTab"))
        self.createAssetBtn = QtGui.QPushButton(self.assetCreatorTab)
        self.createAssetBtn.setGeometry(QtCore.QRect(340, 780, 221, 23))
        self.createAssetBtn.setObjectName(_fromUtf8("createAssetBtn"))
        self.departmentCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.departmentCreationList.setGeometry(QtCore.QRect(30, 80, 121, 192))
        self.departmentCreationList.setFrameShape(QtGui.QFrame.Box)
        self.departmentCreationList.setObjectName(_fromUtf8("departmentCreationList"))
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.departmentCreationList.addItem(item)
        self.softwareCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.softwareCreationList.setGeometry(QtCore.QRect(210, 70, 121, 192))
        self.softwareCreationList.setFrameShape(QtGui.QFrame.Box)
        self.softwareCreationList.setObjectName(_fromUtf8("softwareCreationList"))
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.softwareCreationList.addItem(item)
        self.assetNameCreationLineEdit = QtGui.QLineEdit(self.assetCreatorTab)
        self.assetNameCreationLineEdit.setGeometry(QtCore.QRect(440, 680, 113, 20))
        self.assetNameCreationLineEdit.setObjectName(_fromUtf8("assetNameCreationLineEdit"))
        self.assetNameCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.assetNameCreationLbl.setGeometry(QtCore.QRect(350, 690, 81, 16))
        self.assetNameCreationLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.assetNameCreationLbl.setObjectName(_fromUtf8("assetNameCreationLbl"))
        self.assetDependencyList = QtGui.QListWidget(self.assetCreatorTab)
        self.assetDependencyList.setEnabled(True)
        self.assetDependencyList.setGeometry(QtCore.QRect(850, 90, 161, 192))
        self.assetDependencyList.setFrameShape(QtGui.QFrame.Box)
        self.assetDependencyList.setObjectName(_fromUtf8("assetDependencyList"))
        self.seqCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.seqCreationList.setGeometry(QtCore.QRect(370, 90, 181, 192))
        self.seqCreationList.setFrameShape(QtGui.QFrame.Box)
        self.seqCreationList.setObjectName(_fromUtf8("seqCreationList"))
        self.sequencesCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.sequencesCreationLbl.setGeometry(QtCore.QRect(380, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequencesCreationLbl.setFont(font)
        self.sequencesCreationLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.sequencesCreationLbl.setObjectName(_fromUtf8("sequencesCreationLbl"))
        self.dependencyCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.dependencyCreationLbl.setGeometry(QtCore.QRect(830, 60, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dependencyCreationLbl.setFont(font)
        self.dependencyCreationLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.dependencyCreationLbl.setObjectName(_fromUtf8("dependencyCreationLbl"))
        self.departmentCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.departmentCreationLbl.setGeometry(QtCore.QRect(30, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.departmentCreationLbl.setFont(font)
        self.departmentCreationLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.departmentCreationLbl.setObjectName(_fromUtf8("departmentCreationLbl"))
        self.softwareCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.softwareCreationLbl.setGeometry(QtCore.QRect(220, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.softwareCreationLbl.setFont(font)
        self.softwareCreationLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.softwareCreationLbl.setObjectName(_fromUtf8("softwareCreationLbl"))
        self.shotCreationList = QtGui.QListWidget(self.assetCreatorTab)
        self.shotCreationList.setGeometry(QtCore.QRect(580, 90, 181, 192))
        self.shotCreationList.setFrameShape(QtGui.QFrame.Box)
        self.shotCreationList.setObjectName(_fromUtf8("shotCreationList"))
        self.shotCreationLbl = QtGui.QLabel(self.assetCreatorTab)
        self.shotCreationLbl.setGeometry(QtCore.QRect(590, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shotCreationLbl.setFont(font)
        self.shotCreationLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.shotCreationLbl.setObjectName(_fromUtf8("shotCreationLbl"))
        self.Tabs.addTab(self.assetCreatorTab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.referenceToolMainFrame = QtGui.QFrame(self.tab)
        self.referenceToolMainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.referenceToolMainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.referenceToolMainFrame.setObjectName(_fromUtf8("referenceToolMainFrame"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.referenceToolMainFrame)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.referenceOptionsFrame = QtGui.QFrame(self.referenceToolMainFrame)
        self.referenceOptionsFrame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.referenceOptionsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.referenceOptionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.referenceOptionsFrame.setObjectName(_fromUtf8("referenceOptionsFrame"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.referenceOptionsFrame)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.addReferenceFrame = QtGui.QFrame(self.referenceOptionsFrame)
        self.addReferenceFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addReferenceFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addReferenceFrame.setObjectName(_fromUtf8("addReferenceFrame"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.addReferenceFrame)
        self.verticalLayout_17.setMargin(5)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.seqAndShotsFrame = QtGui.QFrame(self.addReferenceFrame)
        self.seqAndShotsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.seqAndShotsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.seqAndShotsFrame.setObjectName(_fromUtf8("seqAndShotsFrame"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.seqAndShotsFrame)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.seqReferenceFrame = QtGui.QFrame(self.seqAndShotsFrame)
        self.seqReferenceFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.seqReferenceFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.seqReferenceFrame.setObjectName(_fromUtf8("seqReferenceFrame"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.seqReferenceFrame)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.sequencesReferenceLbl = QtGui.QLabel(self.seqReferenceFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequencesReferenceLbl.setFont(font)
        self.sequencesReferenceLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.sequencesReferenceLbl.setObjectName(_fromUtf8("sequencesReferenceLbl"))
        self.verticalLayout_15.addWidget(self.sequencesReferenceLbl)
        self.seqReferenceList = QtGui.QListWidget(self.seqReferenceFrame)
        self.seqReferenceList.setFrameShape(QtGui.QFrame.Box)
        self.seqReferenceList.setObjectName(_fromUtf8("seqReferenceList"))
        self.verticalLayout_15.addWidget(self.seqReferenceList)
        self.horizontalLayout_26.addWidget(self.seqReferenceFrame)
        self.shotReferenceFrame = QtGui.QFrame(self.seqAndShotsFrame)
        self.shotReferenceFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.shotReferenceFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.shotReferenceFrame.setObjectName(_fromUtf8("shotReferenceFrame"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.shotReferenceFrame)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.shotReferenceLbl = QtGui.QLabel(self.shotReferenceFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shotReferenceLbl.setFont(font)
        self.shotReferenceLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.shotReferenceLbl.setObjectName(_fromUtf8("shotReferenceLbl"))
        self.verticalLayout_16.addWidget(self.shotReferenceLbl)
        self.shotReferenceList = QtGui.QListWidget(self.shotReferenceFrame)
        self.shotReferenceList.setFrameShape(QtGui.QFrame.Box)
        self.shotReferenceList.setObjectName(_fromUtf8("shotReferenceList"))
        self.verticalLayout_16.addWidget(self.shotReferenceList)
        self.horizontalLayout_26.addWidget(self.shotReferenceFrame)
        self.verticalLayout_17.addWidget(self.seqAndShotsFrame)
        self.addReferenceOptionsFrame = QtGui.QFrame(self.addReferenceFrame)
        self.addReferenceOptionsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addReferenceOptionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addReferenceOptionsFrame.setObjectName(_fromUtf8("addReferenceOptionsFrame"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.addReferenceOptionsFrame)
        self.horizontalLayout_27.setMargin(2)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.fromWebGroupBox = QtGui.QGroupBox(self.addReferenceOptionsFrame)
        self.fromWebGroupBox.setFlat(True)
        self.fromWebGroupBox.setCheckable(False)
        self.fromWebGroupBox.setObjectName(_fromUtf8("fromWebGroupBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.fromWebGroupBox)
        self.verticalLayout_13.setMargin(3)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.frame_7 = QtGui.QFrame(self.fromWebGroupBox)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_34.setMargin(0)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.referenceWebLineEdit = QtGui.QLineEdit(self.frame_7)
        self.referenceWebLineEdit.setEnabled(True)
        self.referenceWebLineEdit.setObjectName(_fromUtf8("referenceWebLineEdit"))
        self.horizontalLayout_34.addWidget(self.referenceWebLineEdit)
        self.showUrlImageBtn = QtGui.QPushButton(self.frame_7)
        self.showUrlImageBtn.setMaximumSize(QtCore.QSize(24, 24))
        self.showUrlImageBtn.setText(_fromUtf8(""))
        self.showUrlImageBtn.setIconSize(QtCore.QSize(16, 16))
        self.showUrlImageBtn.setObjectName(_fromUtf8("showUrlImageBtn"))
        self.horizontalLayout_34.addWidget(self.showUrlImageBtn)
        self.verticalLayout_13.addWidget(self.frame_7)
        self.referenceNameFrame = QtGui.QFrame(self.fromWebGroupBox)
        self.referenceNameFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.referenceNameFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.referenceNameFrame.setObjectName(_fromUtf8("referenceNameFrame"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.referenceNameFrame)
        self.horizontalLayout_25.setMargin(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.referenceNameLbl = QtGui.QLabel(self.referenceNameFrame)
        self.referenceNameLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.referenceNameLbl.setObjectName(_fromUtf8("referenceNameLbl"))
        self.horizontalLayout_25.addWidget(self.referenceNameLbl)
        self.referenceNameLineEdit = QtGui.QLineEdit(self.referenceNameFrame)
        self.referenceNameLineEdit.setObjectName(_fromUtf8("referenceNameLineEdit"))
        self.horizontalLayout_25.addWidget(self.referenceNameLineEdit)
        self.verticalLayout_13.addWidget(self.referenceNameFrame)
        self.createReferenceFromWebBtn = QtGui.QPushButton(self.fromWebGroupBox)
        self.createReferenceFromWebBtn.setObjectName(_fromUtf8("createReferenceFromWebBtn"))
        self.verticalLayout_13.addWidget(self.createReferenceFromWebBtn)
        self.horizontalLayout_27.addWidget(self.fromWebGroupBox)
        self.referenceCreationLine = QtGui.QFrame(self.addReferenceOptionsFrame)
        self.referenceCreationLine.setFrameShape(QtGui.QFrame.VLine)
        self.referenceCreationLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.referenceCreationLine.setObjectName(_fromUtf8("referenceCreationLine"))
        self.horizontalLayout_27.addWidget(self.referenceCreationLine)
        self.fromExistingFilesGroupBox = QtGui.QGroupBox(self.addReferenceOptionsFrame)
        self.fromExistingFilesGroupBox.setFlat(True)
        self.fromExistingFilesGroupBox.setCheckable(False)
        self.fromExistingFilesGroupBox.setChecked(False)
        self.fromExistingFilesGroupBox.setObjectName(_fromUtf8("fromExistingFilesGroupBox"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.fromExistingFilesGroupBox)
        self.verticalLayout_14.setMargin(3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.createReferencesFromFilesBtn = QtGui.QPushButton(self.fromExistingFilesGroupBox)
        self.createReferencesFromFilesBtn.setEnabled(True)
        self.createReferencesFromFilesBtn.setObjectName(_fromUtf8("createReferencesFromFilesBtn"))
        self.verticalLayout_14.addWidget(self.createReferencesFromFilesBtn)
        self.horizontalLayout_27.addWidget(self.fromExistingFilesGroupBox)
        self.verticalLayout_17.addWidget(self.addReferenceOptionsFrame)
        self.changeRefSeqShotBtn = QtGui.QPushButton(self.addReferenceFrame)
        self.changeRefSeqShotBtn.setObjectName(_fromUtf8("changeRefSeqShotBtn"))
        self.verticalLayout_17.addWidget(self.changeRefSeqShotBtn)
        self.verticalLayout_21.addWidget(self.addReferenceFrame)
        self.filterByFrame = QtGui.QFrame(self.referenceOptionsFrame)
        self.filterByFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.filterByFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.filterByFrame.setObjectName(_fromUtf8("filterByFrame"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.filterByFrame)
        self.verticalLayout_12.setMargin(5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.filterByTagsGroupBox = QtGui.QGroupBox(self.filterByFrame)
        self.filterByTagsGroupBox.setFlat(True)
        self.filterByTagsGroupBox.setObjectName(_fromUtf8("filterByTagsGroupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.filterByTagsGroupBox)
        self.verticalLayout_10.setMargin(3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.filterByTagsListWidget = QtGui.QListWidget(self.filterByTagsGroupBox)
        self.filterByTagsListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.filterByTagsListWidget.setObjectName(_fromUtf8("filterByTagsListWidget"))
        self.verticalLayout_10.addWidget(self.filterByTagsListWidget)
        self.verticalLayout_12.addWidget(self.filterByTagsGroupBox)
        self.verticalLayout_21.addWidget(self.filterByFrame)
        self.addTagsFrame = QtGui.QFrame(self.referenceOptionsFrame)
        self.addTagsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addTagsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addTagsFrame.setObjectName(_fromUtf8("addTagsFrame"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.addTagsFrame)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.addTagsGroupBox = QtGui.QGroupBox(self.addTagsFrame)
        self.addTagsGroupBox.setFlat(True)
        self.addTagsGroupBox.setObjectName(_fromUtf8("addTagsGroupBox"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.addTagsGroupBox)
        self.horizontalLayout_24.setMargin(3)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.allTagsListWidget = QtGui.QListWidget(self.addTagsGroupBox)
        self.allTagsListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.allTagsListWidget.setObjectName(_fromUtf8("allTagsListWidget"))
        self.horizontalLayout_24.addWidget(self.allTagsListWidget)
        self.frame = QtGui.QFrame(self.addTagsGroupBox)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_50 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_50.setMargin(0)
        self.verticalLayout_50.setObjectName(_fromUtf8("verticalLayout_50"))
        self.addTagsBtn = QtGui.QPushButton(self.frame)
        self.addTagsBtn.setObjectName(_fromUtf8("addTagsBtn"))
        self.verticalLayout_50.addWidget(self.addTagsBtn)
        self.removeTagsBtn = QtGui.QPushButton(self.frame)
        self.removeTagsBtn.setObjectName(_fromUtf8("removeTagsBtn"))
        self.verticalLayout_50.addWidget(self.removeTagsBtn)
        self.horizontalLayout_24.addWidget(self.frame)
        self.existingTagsListWidget = QtGui.QListWidget(self.addTagsGroupBox)
        self.existingTagsListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.existingTagsListWidget.setObjectName(_fromUtf8("existingTagsListWidget"))
        self.horizontalLayout_24.addWidget(self.existingTagsListWidget)
        self.verticalLayout_18.addWidget(self.addTagsGroupBox)
        self.verticalLayout_21.addWidget(self.addTagsFrame)
        self.openInFrame = QtGui.QFrame(self.referenceOptionsFrame)
        self.openInFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.openInFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.openInFrame.setObjectName(_fromUtf8("openInFrame"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.openInFrame)
        self.verticalLayout_19.setMargin(5)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.openInGroupBox = QtGui.QGroupBox(self.openInFrame)
        self.openInGroupBox.setFlat(True)
        self.openInGroupBox.setObjectName(_fromUtf8("openInGroupBox"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.openInGroupBox)
        self.horizontalLayout_28.setMargin(2)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.openRefInPhotoshopBtn = QtGui.QPushButton(self.openInGroupBox)
        self.openRefInPhotoshopBtn.setObjectName(_fromUtf8("openRefInPhotoshopBtn"))
        self.horizontalLayout_28.addWidget(self.openRefInPhotoshopBtn)
        self.openRefInKuadroBtn = QtGui.QPushButton(self.openInGroupBox)
        self.openRefInKuadroBtn.setObjectName(_fromUtf8("openRefInKuadroBtn"))
        self.horizontalLayout_28.addWidget(self.openRefInKuadroBtn)
        self.verticalLayout_19.addWidget(self.openInGroupBox)
        self.verticalLayout_21.addWidget(self.openInFrame)
        self.horizontalLayout_23.addWidget(self.referenceOptionsFrame)
        self.referenceThumbFrame = QtGui.QFrame(self.referenceToolMainFrame)
        self.referenceThumbFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.referenceThumbFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.referenceThumbFrame.setObjectName(_fromUtf8("referenceThumbFrame"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.referenceThumbFrame)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.referenceThumbListWidget = QtGui.QListWidget(self.referenceThumbFrame)
        self.referenceThumbListWidget.setMinimumSize(QtCore.QSize(675, 0))
        self.referenceThumbListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.referenceThumbListWidget.setIconSize(QtCore.QSize(256, 256))
        self.referenceThumbListWidget.setMovement(QtGui.QListView.Static)
        self.referenceThumbListWidget.setFlow(QtGui.QListView.LeftToRight)
        self.referenceThumbListWidget.setProperty("isWrapping", True)
        self.referenceThumbListWidget.setResizeMode(QtGui.QListView.Adjust)
        self.referenceThumbListWidget.setLayoutMode(QtGui.QListView.SinglePass)
        self.referenceThumbListWidget.setViewMode(QtGui.QListView.IconMode)
        self.referenceThumbListWidget.setUniformItemSizes(True)
        self.referenceThumbListWidget.setBatchSize(500)
        self.referenceThumbListWidget.setWordWrap(True)
        self.referenceThumbListWidget.setObjectName(_fromUtf8("referenceThumbListWidget"))
        self.verticalLayout_20.addWidget(self.referenceThumbListWidget)
        self.referenceThumbSizeSlider = QtGui.QSlider(self.referenceThumbFrame)
        self.referenceThumbSizeSlider.setMinimum(256)
        self.referenceThumbSizeSlider.setMaximum(1024)
        self.referenceThumbSizeSlider.setProperty("value", 256)
        self.referenceThumbSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.referenceThumbSizeSlider.setObjectName(_fromUtf8("referenceThumbSizeSlider"))
        self.verticalLayout_20.addWidget(self.referenceThumbSizeSlider)
        self.removeRefsBtn = QtGui.QPushButton(self.referenceThumbFrame)
        self.removeRefsBtn.setObjectName(_fromUtf8("removeRefsBtn"))
        self.verticalLayout_20.addWidget(self.removeRefsBtn)
        self.horizontalLayout_23.addWidget(self.referenceThumbFrame)
        self.verticalLayout_23.addWidget(self.referenceToolMainFrame)
        self.progressBarFrame = QtGui.QFrame(self.tab)
        self.progressBarFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.progressBarFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.progressBarFrame.setObjectName(_fromUtf8("progressBarFrame"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.progressBarFrame)
        self.verticalLayout_22.setMargin(0)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_23.addWidget(self.progressBarFrame)
        self.Tabs.addTab(self.tab, _fromUtf8(""))
        self.tagsManagerTab = QtGui.QWidget()
        self.tagsManagerTab.setEnabled(True)
        self.tagsManagerTab.setObjectName(_fromUtf8("tagsManagerTab"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.tagsManagerTab)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.tagsManagerTab)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_25.addWidget(self.treeWidget_2)
        self.tagsListWidget = QtGui.QListWidget(self.tagsManagerTab)
        self.tagsListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tagsListWidget.setObjectName(_fromUtf8("tagsListWidget"))
        self.verticalLayout_25.addWidget(self.tagsListWidget)
        self.addTagLineEdit = QtGui.QLineEdit(self.tagsManagerTab)
        self.addTagLineEdit.setObjectName(_fromUtf8("addTagLineEdit"))
        self.verticalLayout_25.addWidget(self.addTagLineEdit)
        self.addTagBtn = QtGui.QPushButton(self.tagsManagerTab)
        self.addTagBtn.setObjectName(_fromUtf8("addTagBtn"))
        self.verticalLayout_25.addWidget(self.addTagBtn)
        self.removeSelectedTagsBtn = QtGui.QPushButton(self.tagsManagerTab)
        self.removeSelectedTagsBtn.setObjectName(_fromUtf8("removeSelectedTagsBtn"))
        self.verticalLayout_25.addWidget(self.removeSelectedTagsBtn)
        self.Tabs.addTab(self.tagsManagerTab, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.logTab)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.logTextEdit = QtGui.QTextEdit(self.logTab)
        self.logTextEdit.setFrameShape(QtGui.QFrame.Box)
        self.logTextEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.logTextEdit.setLineWidth(1)
        self.logTextEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setAcceptRichText(True)
        self.logTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logTextEdit.setObjectName(_fromUtf8("logTextEdit"))
        self.verticalLayout_24.addWidget(self.logTextEdit)
        self.updateLogBtn = QtGui.QPushButton(self.logTab)
        self.updateLogBtn.setObjectName(_fromUtf8("updateLogBtn"))
        self.verticalLayout_24.addWidget(self.updateLogBtn)
        self.logLbl = QtGui.QLabel(self.logTab)
        self.logLbl.setObjectName(_fromUtf8("logLbl"))
        self.verticalLayout_24.addWidget(self.logLbl)
        self.Tabs.addTab(self.logTab, _fromUtf8(""))
        self.preferencesTab = QtGui.QWidget()
        self.preferencesTab.setObjectName(_fromUtf8("preferencesTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.preferencesTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.softwarePathGrpBox = QtGui.QGroupBox(self.preferencesTab)
        self.softwarePathGrpBox.setObjectName(_fromUtf8("softwarePathGrpBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.softwarePathGrpBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.photoshopPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.photoshopPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.photoshopPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.photoshopPathFrame.setLineWidth(1)
        self.photoshopPathFrame.setObjectName(_fromUtf8("photoshopPathFrame"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.photoshopPathFrame)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.photoshopPrefLbl = QtGui.QLabel(self.photoshopPathFrame)
        self.photoshopPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.photoshopPrefLbl.setObjectName(_fromUtf8("photoshopPrefLbl"))
        self.horizontalLayout_7.addWidget(self.photoshopPrefLbl)
        self.photoshopPathLineEdit = QtGui.QLineEdit(self.photoshopPathFrame)
        self.photoshopPathLineEdit.setText(_fromUtf8(""))
        self.photoshopPathLineEdit.setObjectName(_fromUtf8("photoshopPathLineEdit"))
        self.horizontalLayout_7.addWidget(self.photoshopPathLineEdit)
        self.verticalLayout_6.addWidget(self.photoshopPathFrame)
        self.mayaPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.mayaPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mayaPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.mayaPathFrame.setLineWidth(1)
        self.mayaPathFrame.setObjectName(_fromUtf8("mayaPathFrame"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.mayaPathFrame)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mayaPrefLbl = QtGui.QLabel(self.mayaPathFrame)
        self.mayaPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.mayaPrefLbl.setObjectName(_fromUtf8("mayaPrefLbl"))
        self.horizontalLayout_8.addWidget(self.mayaPrefLbl)
        self.mayaPathLineEdit = QtGui.QLineEdit(self.mayaPathFrame)
        self.mayaPathLineEdit.setText(_fromUtf8(""))
        self.mayaPathLineEdit.setObjectName(_fromUtf8("mayaPathLineEdit"))
        self.horizontalLayout_8.addWidget(self.mayaPathLineEdit)
        self.verticalLayout_6.addWidget(self.mayaPathFrame)
        self.softimagePathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.softimagePathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.softimagePathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.softimagePathFrame.setLineWidth(1)
        self.softimagePathFrame.setObjectName(_fromUtf8("softimagePathFrame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.softimagePathFrame)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.softimagePrefLbl = QtGui.QLabel(self.softimagePathFrame)
        self.softimagePrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.softimagePrefLbl.setObjectName(_fromUtf8("softimagePrefLbl"))
        self.horizontalLayout_9.addWidget(self.softimagePrefLbl)
        self.softimagePathLineEdit = QtGui.QLineEdit(self.softimagePathFrame)
        self.softimagePathLineEdit.setText(_fromUtf8(""))
        self.softimagePathLineEdit.setObjectName(_fromUtf8("softimagePathLineEdit"))
        self.horizontalLayout_9.addWidget(self.softimagePathLineEdit)
        self.verticalLayout_6.addWidget(self.softimagePathFrame)
        self.houdiniPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.houdiniPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.houdiniPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.houdiniPathFrame.setLineWidth(1)
        self.houdiniPathFrame.setObjectName(_fromUtf8("houdiniPathFrame"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.houdiniPathFrame)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.houdiniPrefLbl = QtGui.QLabel(self.houdiniPathFrame)
        self.houdiniPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.houdiniPrefLbl.setObjectName(_fromUtf8("houdiniPrefLbl"))
        self.horizontalLayout_10.addWidget(self.houdiniPrefLbl)
        self.houdiniPathLineEdit = QtGui.QLineEdit(self.houdiniPathFrame)
        self.houdiniPathLineEdit.setText(_fromUtf8(""))
        self.houdiniPathLineEdit.setObjectName(_fromUtf8("houdiniPathLineEdit"))
        self.horizontalLayout_10.addWidget(self.houdiniPathLineEdit)
        self.verticalLayout_6.addWidget(self.houdiniPathFrame)
        self.cinema4dPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.cinema4dPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.cinema4dPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.cinema4dPathFrame.setLineWidth(1)
        self.cinema4dPathFrame.setObjectName(_fromUtf8("cinema4dPathFrame"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.cinema4dPathFrame)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cinema4dPrefLbl = QtGui.QLabel(self.cinema4dPathFrame)
        self.cinema4dPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.cinema4dPrefLbl.setObjectName(_fromUtf8("cinema4dPrefLbl"))
        self.horizontalLayout_11.addWidget(self.cinema4dPrefLbl)
        self.cinema4dPathLineEdit = QtGui.QLineEdit(self.cinema4dPathFrame)
        self.cinema4dPathLineEdit.setText(_fromUtf8(""))
        self.cinema4dPathLineEdit.setObjectName(_fromUtf8("cinema4dPathLineEdit"))
        self.horizontalLayout_11.addWidget(self.cinema4dPathLineEdit)
        self.verticalLayout_6.addWidget(self.cinema4dPathFrame)
        self.nukePathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.nukePathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.nukePathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.nukePathFrame.setLineWidth(1)
        self.nukePathFrame.setObjectName(_fromUtf8("nukePathFrame"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.nukePathFrame)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.nukePrefLbl = QtGui.QLabel(self.nukePathFrame)
        self.nukePrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.nukePrefLbl.setObjectName(_fromUtf8("nukePrefLbl"))
        self.horizontalLayout_12.addWidget(self.nukePrefLbl)
        self.nukePathLineEdit = QtGui.QLineEdit(self.nukePathFrame)
        self.nukePathLineEdit.setText(_fromUtf8(""))
        self.nukePathLineEdit.setObjectName(_fromUtf8("nukePathLineEdit"))
        self.horizontalLayout_12.addWidget(self.nukePathLineEdit)
        self.verticalLayout_6.addWidget(self.nukePathFrame)
        self.zbrushPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.zbrushPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.zbrushPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.zbrushPathFrame.setLineWidth(1)
        self.zbrushPathFrame.setObjectName(_fromUtf8("zbrushPathFrame"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.zbrushPathFrame)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.zbrushPrefLbl = QtGui.QLabel(self.zbrushPathFrame)
        self.zbrushPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.zbrushPrefLbl.setObjectName(_fromUtf8("zbrushPrefLbl"))
        self.horizontalLayout_19.addWidget(self.zbrushPrefLbl)
        self.zbrushPathLineEdit = QtGui.QLineEdit(self.zbrushPathFrame)
        self.zbrushPathLineEdit.setText(_fromUtf8(""))
        self.zbrushPathLineEdit.setObjectName(_fromUtf8("zbrushPathLineEdit"))
        self.horizontalLayout_19.addWidget(self.zbrushPathLineEdit)
        self.verticalLayout_6.addWidget(self.zbrushPathFrame)
        self.mariPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.mariPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mariPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.mariPathFrame.setLineWidth(1)
        self.mariPathFrame.setObjectName(_fromUtf8("mariPathFrame"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.mariPathFrame)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.mariPrefLbl = QtGui.QLabel(self.mariPathFrame)
        self.mariPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.mariPrefLbl.setObjectName(_fromUtf8("mariPrefLbl"))
        self.horizontalLayout_21.addWidget(self.mariPrefLbl)
        self.mariPathLineEdit = QtGui.QLineEdit(self.mariPathFrame)
        self.mariPathLineEdit.setText(_fromUtf8(""))
        self.mariPathLineEdit.setObjectName(_fromUtf8("mariPathLineEdit"))
        self.horizontalLayout_21.addWidget(self.mariPathLineEdit)
        self.verticalLayout_6.addWidget(self.mariPathFrame)
        self.blenderPathFrame = QtGui.QFrame(self.softwarePathGrpBox)
        self.blenderPathFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.blenderPathFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.blenderPathFrame.setLineWidth(1)
        self.blenderPathFrame.setObjectName(_fromUtf8("blenderPathFrame"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.blenderPathFrame)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.blenderPrefLbl = QtGui.QLabel(self.blenderPathFrame)
        self.blenderPrefLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.blenderPrefLbl.setObjectName(_fromUtf8("blenderPrefLbl"))
        self.horizontalLayout_22.addWidget(self.blenderPrefLbl)
        self.blenderPathLineEdit = QtGui.QLineEdit(self.blenderPathFrame)
        self.blenderPathLineEdit.setText(_fromUtf8(""))
        self.blenderPathLineEdit.setObjectName(_fromUtf8("blenderPathLineEdit"))
        self.horizontalLayout_22.addWidget(self.blenderPathLineEdit)
        self.verticalLayout_6.addWidget(self.blenderPathFrame)
        self.verticalLayout_7.addWidget(self.softwarePathGrpBox)
        self.savePrefBtn = QtGui.QPushButton(self.preferencesTab)
        self.savePrefBtn.setObjectName(_fromUtf8("savePrefBtn"))
        self.verticalLayout_7.addWidget(self.savePrefBtn)
        self.Tabs.addTab(self.preferencesTab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.Tabs)
        self.deadlineProgressBar = QtGui.QProgressBar(self.assetManagerFrame)
        self.deadlineProgressBar.setProperty("value", 100)
        self.deadlineProgressBar.setObjectName(_fromUtf8("deadlineProgressBar"))
        self.verticalLayout_5.addWidget(self.deadlineProgressBar)
        self.horizontalLayout_3.addWidget(self.assetManagerFrame)

        self.retranslateUi(Form)
        self.Tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        return Form

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Asset Manager", None))
        self.filterGroupBox.setTitle(_translate("Form", "Filter options", None))
        self.assignedToFilterLbl.setText(_translate("Form", "Assigned to:", None))
        self.assignedToFilterComboBox.setItemText(0, _translate("Form", "None", None))
        self.assignedToFilterComboBox.setItemText(1, _translate("Form", "Amélie", None))
        self.assignedToFilterComboBox.setItemText(2, _translate("Form", "Chloé", None))
        self.assignedToFilterComboBox.setItemText(3, _translate("Form", "Christopher", None))
        self.assignedToFilterComboBox.setItemText(4, _translate("Form", "David", None))
        self.assignedToFilterComboBox.setItemText(5, _translate("Form", "Edwin", None))
        self.assignedToFilterComboBox.setItemText(6, _translate("Form", "Étienne", None))
        self.assignedToFilterComboBox.setItemText(7, _translate("Form", "Jérémy", None))
        self.assignedToFilterComboBox.setItemText(8, _translate("Form", "Laurence", None))
        self.assignedToFilterComboBox.setItemText(9, _translate("Form", "Louis-Philippe", None))
        self.assignedToFilterComboBox.setItemText(10, _translate("Form", "Marc-Antoine", None))
        self.assignedToFilterComboBox.setItemText(11, _translate("Form", "Mathieu", None))
        self.assignedToFilterComboBox.setItemText(12, _translate("Form", "Maxime", None))
        self.assignedToFilterComboBox.setItemText(13, _translate("Form", "Olivier", None))
        self.assignedToFilterComboBox.setItemText(14, _translate("Form", "Simon", None))
        self.assignedToFilterComboBox.setItemText(15, _translate("Form", "Thibault", None))
        self.assignedToFilterComboBox.setItemText(16, _translate("Form", "Yann", None))
        self.assignedToFilterComboBox.setItemText(17, _translate("Form", "Yi", None))
        self.assignedToFilterComboBox.setItemText(18, _translate("Form", "Valentin", None))
        self.meOnlyCheckBox.setText(_translate("Form", "Me", None))
        self.addProjectLineEdit.setPlaceholderText(_translate("Form", "name", None))
        self.projectShortnameLineEdit.setPlaceholderText(_translate("Form", "shortname", None))
        self.addProjectBtn.setText(_translate("Form", "+", None))
        self.seqFilter.setPlaceholderText(_translate("Form", "filter", None))
        self.seqFilterClearBtn.setText(_translate("Form", "x", None))
        self.assetFilter.setPlaceholderText(_translate("Form", "filter", None))
        self.assetFilterClearBtn.setText(_translate("Form", "x", None))
        self.departmentList.setSortingEnabled(True)
        self.projectList.setSortingEnabled(True)
        self.assetLbl.setText(_translate("Form", "Asset", None))
        self.assetList.setSortingEnabled(True)
        self.departmentLbl.setText(_translate("Form", "Department", None))
        self.projectLbl.setText(_translate("Form", "Project", None))
        self.shotList.setSortingEnabled(False)
        self.seqList.setSortingEnabled(False)
        self.seqLbl.setText(_translate("Form", "Sequence", None))
        self.shotLbl.setText(_translate("Form", "Shot", None))
        self.versionList.setSortingEnabled(True)
        self.versionLbl.setText(_translate("Form", "Version", None))
        self.addSequenceLineEdit.setPlaceholderText(_translate("Form", "sequence name", None))
        self.addSequenceBtn.setText(_translate("Form", "+", None))
        self.addShotBtn.setText(_translate("Form", "+", None))
        self.assetInfoGrp.setTitle(_translate("Form", "Info", None))
        self.fileTypeLbl.setText(_translate("Form", "File Type:", None))
        self.fileTypeValueLbl.setText(_translate("Form", "...", None))
        self.thumbnailLbl.setText(_translate("Form", "Thumbnail", None))
        self.updateThumbBtn.setText(_translate("Form", "Update Thumbnail", None))
        self.openInExplorerBtn.setText(_translate("Form", "Open in Explorer", None))
        self.createdByLbl.setText(_translate("Form", "Created by:", None))
        self.createdByValueLbl.setText(_translate("Form", "...", None))
        self.assignedToLbl.setText(_translate("Form", "Assigned to:", None))
        self.assignedToValueLbl.setText(_translate("Form", "...", None))
        self.dueDateLbl.setText(_translate("Form", "Due on:", None))
        self.dueDateValueLbl.setText(_translate("Form", "Lundi 01 Janvier 2015 - 12h00", None))
        self.timeLeftLbl.setText(_translate("Form", "1 day 10 hours left", None))
        self.statusLbl.setText(_translate("Form", "Status:", None))
        self.label.setText(_translate("Form", "Approved", None))
        self.statusLbl_2.setText(_translate("Form", "Last accessed by:", None))
        self.label_2.setText(_translate("Form", "Thibault on monday June 15 2015", None))
        self.commentsLbl.setText(_translate("Form", "Comments:", None))
        self.addCommentBtn.setText(_translate("Form", "Add comment", None))
        self.actionGrpBox.setTitle(_translate("Form", "Action", None))
        self.createVersionBtn.setText(_translate("Form", "Create version", None))
        self.publishBtn.setText(_translate("Form", "Publish", None))
        self.loadBtn.setText(_translate("Form", "Load Asset", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.assetLoaderTab), _translate("Form", "Asset Loader", None))
        self.tmFilterByGroupBox.setTitle(_translate("Form", "Filter by", None))
        self.tmProjectLbl.setText(_translate("Form", "Project:", None))
        self.tmSequenceLbl.setText(_translate("Form", "Sequence:", None))
        self.tmShotLbl.setText(_translate("Form", "Shot:", None))
        self.tmDepartmentFilter.setText(_translate("Form", "Department:", None))
        self.tmStatusLbl.setText(_translate("Form", "Status:", None))
        self.tmMemberLbl.setText(_translate("Form", "Member:", None))
        self.tmBidLbl.setText(_translate("Form", "Bid:", None))
        self.tmBidOperationComboBox.setItemText(0, _translate("Form", ">", None))
        self.tmBidOperationComboBox.setItemText(1, _translate("Form", "<", None))
        self.tmTaskManagementFrame.setTitle(_translate("Form", "Tasks Management", None))
        self.tmAddTaskBtn.setText(_translate("Form", "Add Task(s)", None))
        self.tmCompleteTaskBtn.setText(_translate("Form", "Complete Task(s)", None))
        self.tmRemoveTaskBtn.setText(_translate("Form", "Remove Task(s)", None))
        self.tmTableWidget.setSortingEnabled(False)
        item = self.tmTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Task Name", None))
        item = self.tmTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Department", None))
        item = self.tmTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Status", None))
        item = self.tmTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Assigned to", None))
        item = self.tmTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Start", None))
        item = self.tmTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "End", None))
        item = self.tmTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Days Left", None))
        item = self.tmTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Bid (hours)", None))
        item = self.tmTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Sequence", None))
        item = self.tmTableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Shot", None))
        item = self.tmTableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Asset", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tmTab), _translate("Form", "Task Manager", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.myTasksTab), _translate("Form", "My Tasks", None))
        self.createAssetBtn.setText(_translate("Form", "Create Asset", None))
        self.departmentCreationList.setSortingEnabled(True)
        __sortingEnabled = self.departmentCreationList.isSortingEnabled()
        self.departmentCreationList.setSortingEnabled(False)
        item = self.departmentCreationList.item(0)
        item.setText(_translate("Form", "Concepts", None))
        item = self.departmentCreationList.item(1)
        item.setText(_translate("Form", "Layout", None))
        item = self.departmentCreationList.item(2)
        item.setText(_translate("Form", "Modeling", None))
        item = self.departmentCreationList.item(3)
        item.setText(_translate("Form", "References", None))
        self.departmentCreationList.setSortingEnabled(__sortingEnabled)
        self.softwareCreationList.setSortingEnabled(True)
        __sortingEnabled = self.softwareCreationList.isSortingEnabled()
        self.softwareCreationList.setSortingEnabled(False)
        item = self.softwareCreationList.item(0)
        item.setText(_translate("Form", "Blender", None))
        item = self.softwareCreationList.item(1)
        item.setText(_translate("Form", "Cinema 4D", None))
        item = self.softwareCreationList.item(2)
        item.setText(_translate("Form", "Houdini", None))
        item = self.softwareCreationList.item(3)
        item.setText(_translate("Form", "Maya", None))
        item = self.softwareCreationList.item(4)
        item.setText(_translate("Form", "Photoshop", None))
        item = self.softwareCreationList.item(5)
        item.setText(_translate("Form", "Softimage", None))
        item = self.softwareCreationList.item(6)
        item.setText(_translate("Form", "ZBrush", None))
        self.softwareCreationList.setSortingEnabled(__sortingEnabled)
        self.assetNameCreationLineEdit.setPlaceholderText(_translate("Form", "ex: mainchar, house...", None))
        self.assetNameCreationLbl.setText(_translate("Form", "Asset name:", None))
        self.assetDependencyList.setSortingEnabled(True)
        self.seqCreationList.setSortingEnabled(True)
        self.sequencesCreationLbl.setText(_translate("Form", "Sequences", None))
        self.dependencyCreationLbl.setText(_translate("Form", "Dependency", None))
        self.departmentCreationLbl.setText(_translate("Form", "Departments", None))
        self.softwareCreationLbl.setText(_translate("Form", "Software", None))
        self.shotCreationList.setSortingEnabled(False)
        self.shotCreationLbl.setText(_translate("Form", "Shots", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.assetCreatorTab), _translate("Form", "Asset Creator", None))
        self.sequencesReferenceLbl.setText(_translate("Form", "Sequences", None))
        self.seqReferenceList.setSortingEnabled(True)
        self.shotReferenceLbl.setText(_translate("Form", "Shots", None))
        self.shotReferenceList.setSortingEnabled(False)
        self.fromWebGroupBox.setTitle(_translate("Form", "From web", None))
        self.referenceWebLineEdit.setPlaceholderText(_translate("Form", "URL", None))
        self.referenceNameLbl.setText(_translate("Form", "Asset name:", None))
        self.referenceNameLineEdit.setPlaceholderText(_translate("Form", "ex: mainchar, house...", None))
        self.createReferenceFromWebBtn.setText(_translate("Form", "Create Reference", None))
        self.fromExistingFilesGroupBox.setTitle(_translate("Form", "From existing files", None))
        self.createReferencesFromFilesBtn.setText(_translate("Form", "Select files on computer", None))
        self.changeRefSeqShotBtn.setText(_translate("Form", "Change sequence / shot for selected ", None))
        self.filterByTagsGroupBox.setTitle(_translate("Form", "Filter by tags", None))
        self.addTagsGroupBox.setTitle(_translate("Form", "Add/remove tags", None))
        self.allTagsListWidget.setSortingEnabled(True)
        self.addTagsBtn.setText(_translate("Form", ">>", None))
        self.removeTagsBtn.setText(_translate("Form", "<<", None))
        self.openInGroupBox.setTitle(_translate("Form", "Open in", None))
        self.openRefInPhotoshopBtn.setText(_translate("Form", "Photoshop", None))
        self.openRefInKuadroBtn.setText(_translate("Form", "Kuadro", None))
        self.removeRefsBtn.setText(_translate("Form", "Remove Selected Reference(s)", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("Form", "References Tool", None))
        self.addTagLineEdit.setPlaceholderText(_translate("Form", "lighting, statue, architecture, tree, character...", None))
        self.addTagBtn.setText(_translate("Form", "Add tag", None))
        self.removeSelectedTagsBtn.setText(_translate("Form", "Remove selected tags", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tagsManagerTab), _translate("Form", "Tags Manager", None))
        self.logTextEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>", None))
        self.updateLogBtn.setText(_translate("Form", "Update log", None))
        self.logLbl.setText(_translate("Form", "...", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.logTab), _translate("Form", "Log", None))
        self.softwarePathGrpBox.setTitle(_translate("Form", "Software Paths", None))
        self.photoshopPrefLbl.setText(_translate("Form", "Photoshop", None))
        self.photoshopPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.mayaPrefLbl.setText(_translate("Form", "Maya", None))
        self.mayaPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.softimagePrefLbl.setText(_translate("Form", "Softimage", None))
        self.softimagePathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.houdiniPrefLbl.setText(_translate("Form", "Houdini", None))
        self.houdiniPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.cinema4dPrefLbl.setText(_translate("Form", "Cinema 4D", None))
        self.cinema4dPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.nukePrefLbl.setText(_translate("Form", "Nuke", None))
        self.nukePathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.zbrushPrefLbl.setText(_translate("Form", "ZBrush", None))
        self.zbrushPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.mariPrefLbl.setText(_translate("Form", "Mari", None))
        self.mariPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.blenderPrefLbl.setText(_translate("Form", "Blender", None))
        self.blenderPathLineEdit.setPlaceholderText(_translate("Form", "...", None))
        self.savePrefBtn.setText(_translate("Form", "Save Preferences", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.preferencesTab), _translate("Form", "Preferences", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

